// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.5
// source: proto/nietzsche.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NietzscheDB_CreateCollection_FullMethodName     = "/nietzsche.NietzscheDB/CreateCollection"
	NietzscheDB_DropCollection_FullMethodName       = "/nietzsche.NietzscheDB/DropCollection"
	NietzscheDB_ListCollections_FullMethodName      = "/nietzsche.NietzscheDB/ListCollections"
	NietzscheDB_InsertNode_FullMethodName           = "/nietzsche.NietzscheDB/InsertNode"
	NietzscheDB_GetNode_FullMethodName              = "/nietzsche.NietzscheDB/GetNode"
	NietzscheDB_DeleteNode_FullMethodName           = "/nietzsche.NietzscheDB/DeleteNode"
	NietzscheDB_UpdateEnergy_FullMethodName         = "/nietzsche.NietzscheDB/UpdateEnergy"
	NietzscheDB_InsertEdge_FullMethodName           = "/nietzsche.NietzscheDB/InsertEdge"
	NietzscheDB_DeleteEdge_FullMethodName           = "/nietzsche.NietzscheDB/DeleteEdge"
	NietzscheDB_MergeNode_FullMethodName            = "/nietzsche.NietzscheDB/MergeNode"
	NietzscheDB_MergeEdge_FullMethodName            = "/nietzsche.NietzscheDB/MergeEdge"
	NietzscheDB_Query_FullMethodName                = "/nietzsche.NietzscheDB/Query"
	NietzscheDB_KnnSearch_FullMethodName            = "/nietzsche.NietzscheDB/KnnSearch"
	NietzscheDB_Bfs_FullMethodName                  = "/nietzsche.NietzscheDB/Bfs"
	NietzscheDB_Dijkstra_FullMethodName             = "/nietzsche.NietzscheDB/Dijkstra"
	NietzscheDB_Diffuse_FullMethodName              = "/nietzsche.NietzscheDB/Diffuse"
	NietzscheDB_TriggerSleep_FullMethodName         = "/nietzsche.NietzscheDB/TriggerSleep"
	NietzscheDB_InsertSensory_FullMethodName        = "/nietzsche.NietzscheDB/InsertSensory"
	NietzscheDB_GetSensory_FullMethodName           = "/nietzsche.NietzscheDB/GetSensory"
	NietzscheDB_Reconstruct_FullMethodName          = "/nietzsche.NietzscheDB/Reconstruct"
	NietzscheDB_DegradeSensory_FullMethodName       = "/nietzsche.NietzscheDB/DegradeSensory"
	NietzscheDB_InvokeZaratustra_FullMethodName     = "/nietzsche.NietzscheDB/InvokeZaratustra"
	NietzscheDB_BatchInsertNodes_FullMethodName     = "/nietzsche.NietzscheDB/BatchInsertNodes"
	NietzscheDB_BatchInsertEdges_FullMethodName     = "/nietzsche.NietzscheDB/BatchInsertEdges"
	NietzscheDB_RunPageRank_FullMethodName          = "/nietzsche.NietzscheDB/RunPageRank"
	NietzscheDB_RunLouvain_FullMethodName           = "/nietzsche.NietzscheDB/RunLouvain"
	NietzscheDB_RunLabelProp_FullMethodName         = "/nietzsche.NietzscheDB/RunLabelProp"
	NietzscheDB_RunBetweenness_FullMethodName       = "/nietzsche.NietzscheDB/RunBetweenness"
	NietzscheDB_RunCloseness_FullMethodName         = "/nietzsche.NietzscheDB/RunCloseness"
	NietzscheDB_RunDegreeCentrality_FullMethodName  = "/nietzsche.NietzscheDB/RunDegreeCentrality"
	NietzscheDB_RunWCC_FullMethodName               = "/nietzsche.NietzscheDB/RunWCC"
	NietzscheDB_RunSCC_FullMethodName               = "/nietzsche.NietzscheDB/RunSCC"
	NietzscheDB_RunAStar_FullMethodName             = "/nietzsche.NietzscheDB/RunAStar"
	NietzscheDB_RunTriangleCount_FullMethodName     = "/nietzsche.NietzscheDB/RunTriangleCount"
	NietzscheDB_RunJaccardSimilarity_FullMethodName = "/nietzsche.NietzscheDB/RunJaccardSimilarity"
	NietzscheDB_CreateBackup_FullMethodName         = "/nietzsche.NietzscheDB/CreateBackup"
	NietzscheDB_ListBackups_FullMethodName          = "/nietzsche.NietzscheDB/ListBackups"
	NietzscheDB_RestoreBackup_FullMethodName        = "/nietzsche.NietzscheDB/RestoreBackup"
	NietzscheDB_FullTextSearch_FullMethodName       = "/nietzsche.NietzscheDB/FullTextSearch"
	NietzscheDB_SubscribeCDC_FullMethodName         = "/nietzsche.NietzscheDB/SubscribeCDC"
	NietzscheDB_GetStats_FullMethodName             = "/nietzsche.NietzscheDB/GetStats"
	NietzscheDB_HealthCheck_FullMethodName          = "/nietzsche.NietzscheDB/HealthCheck"
)

// NietzscheDBClient is the client API for NietzscheDB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NietzscheDBClient interface {
	// ── Collection management ──────────────────────────────────────────────
	CreateCollection(ctx context.Context, in *CreateCollectionRequest, opts ...grpc.CallOption) (*CreateCollectionResponse, error)
	DropCollection(ctx context.Context, in *DropCollectionRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	ListCollections(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListCollectionsResponse, error)
	// ── Node CRUD ─────────────────────────────────────────────────────────
	InsertNode(ctx context.Context, in *InsertNodeRequest, opts ...grpc.CallOption) (*NodeResponse, error)
	GetNode(ctx context.Context, in *NodeIdRequest, opts ...grpc.CallOption) (*NodeResponse, error)
	DeleteNode(ctx context.Context, in *NodeIdRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	UpdateEnergy(ctx context.Context, in *UpdateEnergyRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// ── Edge CRUD ─────────────────────────────────────────────────────────
	InsertEdge(ctx context.Context, in *InsertEdgeRequest, opts ...grpc.CallOption) (*EdgeResponse, error)
	DeleteEdge(ctx context.Context, in *EdgeIdRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// ── MERGE (upsert semantic: get-or-create) ────────────────────────────────────
	MergeNode(ctx context.Context, in *MergeNodeRequest, opts ...grpc.CallOption) (*MergeNodeResponse, error)
	MergeEdge(ctx context.Context, in *MergeEdgeRequest, opts ...grpc.CallOption) (*MergeEdgeResponse, error)
	// ── NQL query (Nietzsche Query Language) ─────────────────────────────
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	// ── Vector search (hyperbolic KNN) ───────────────────────────────────
	KnnSearch(ctx context.Context, in *KnnRequest, opts ...grpc.CallOption) (*KnnResponse, error)
	// ── Graph traversal ───────────────────────────────────────────────────
	Bfs(ctx context.Context, in *TraversalRequest, opts ...grpc.CallOption) (*TraversalResponse, error)
	Dijkstra(ctx context.Context, in *TraversalRequest, opts ...grpc.CallOption) (*TraversalResponse, error)
	// ── Heat-kernel diffusion (Phase 6) ──────────────────────────────────
	Diffuse(ctx context.Context, in *DiffusionRequest, opts ...grpc.CallOption) (*DiffusionResponse, error)
	// ── Reconsolidation sleep cycle (Phase 8) ────────────────────────────
	TriggerSleep(ctx context.Context, in *SleepRequest, opts ...grpc.CallOption) (*SleepResponse, error)
	// ── Sensory Compression Layer (Phase 11) ─────────────────────────────
	InsertSensory(ctx context.Context, in *InsertSensoryRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	GetSensory(ctx context.Context, in *NodeIdRequest, opts ...grpc.CallOption) (*SensoryResponse, error)
	Reconstruct(ctx context.Context, in *ReconstructRequest, opts ...grpc.CallOption) (*ReconstructResponse, error)
	DegradeSensory(ctx context.Context, in *NodeIdRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// ── Zaratustra — autonomous evolution engine (Phase Z) ───────────────
	InvokeZaratustra(ctx context.Context, in *ZaratustraRequest, opts ...grpc.CallOption) (*ZaratustraResponse, error)
	// ── Batch CRUD ────────────────────────────────────────────────────────
	BatchInsertNodes(ctx context.Context, in *BatchInsertNodesRequest, opts ...grpc.CallOption) (*BatchInsertNodesResponse, error)
	BatchInsertEdges(ctx context.Context, in *BatchInsertEdgesRequest, opts ...grpc.CallOption) (*BatchInsertEdgesResponse, error)
	// ── Graph Algorithms ────────────────────────────────────────────────
	RunPageRank(ctx context.Context, in *PageRankRequest, opts ...grpc.CallOption) (*AlgorithmScoreResponse, error)
	RunLouvain(ctx context.Context, in *LouvainRequest, opts ...grpc.CallOption) (*AlgorithmCommunityResponse, error)
	RunLabelProp(ctx context.Context, in *LabelPropRequest, opts ...grpc.CallOption) (*AlgorithmCommunityResponse, error)
	RunBetweenness(ctx context.Context, in *BetweennessRequest, opts ...grpc.CallOption) (*AlgorithmScoreResponse, error)
	RunCloseness(ctx context.Context, in *ClosenessRequest, opts ...grpc.CallOption) (*AlgorithmScoreResponse, error)
	RunDegreeCentrality(ctx context.Context, in *DegreeCentralityRequest, opts ...grpc.CallOption) (*AlgorithmScoreResponse, error)
	RunWCC(ctx context.Context, in *WccRequest, opts ...grpc.CallOption) (*AlgorithmCommunityResponse, error)
	RunSCC(ctx context.Context, in *SccRequest, opts ...grpc.CallOption) (*AlgorithmCommunityResponse, error)
	RunAStar(ctx context.Context, in *AStarRequest, opts ...grpc.CallOption) (*AStarResponse, error)
	RunTriangleCount(ctx context.Context, in *TriangleCountRequest, opts ...grpc.CallOption) (*TriangleCountResponse, error)
	RunJaccardSimilarity(ctx context.Context, in *JaccardRequest, opts ...grpc.CallOption) (*SimilarityResponse, error)
	// ── Backup/Restore ───────────────────────────────────────────────────
	CreateBackup(ctx context.Context, in *CreateBackupRequest, opts ...grpc.CallOption) (*BackupResponse, error)
	ListBackups(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListBackupsResponse, error)
	RestoreBackup(ctx context.Context, in *RestoreBackupRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// ── Full-Text Search ────────────────────────────────────────────────
	FullTextSearch(ctx context.Context, in *FullTextSearchRequest, opts ...grpc.CallOption) (*FullTextSearchResponse, error)
	// ── Change Data Capture ──────────────────────────────────────────────
	SubscribeCDC(ctx context.Context, in *CdcRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CdcEvent], error)
	// ── Admin ─────────────────────────────────────────────────────────────
	GetStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatsResponse, error)
	HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResponse, error)
}

type nietzscheDBClient struct {
	cc grpc.ClientConnInterface
}

func NewNietzscheDBClient(cc grpc.ClientConnInterface) NietzscheDBClient {
	return &nietzscheDBClient{cc}
}

func (c *nietzscheDBClient) CreateCollection(ctx context.Context, in *CreateCollectionRequest, opts ...grpc.CallOption) (*CreateCollectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCollectionResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_CreateCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) DropCollection(ctx context.Context, in *DropCollectionRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_DropCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) ListCollections(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListCollectionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCollectionsResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_ListCollections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) InsertNode(ctx context.Context, in *InsertNodeRequest, opts ...grpc.CallOption) (*NodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_InsertNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) GetNode(ctx context.Context, in *NodeIdRequest, opts ...grpc.CallOption) (*NodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_GetNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) DeleteNode(ctx context.Context, in *NodeIdRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_DeleteNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) UpdateEnergy(ctx context.Context, in *UpdateEnergyRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_UpdateEnergy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) InsertEdge(ctx context.Context, in *InsertEdgeRequest, opts ...grpc.CallOption) (*EdgeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EdgeResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_InsertEdge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) DeleteEdge(ctx context.Context, in *EdgeIdRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_DeleteEdge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) MergeNode(ctx context.Context, in *MergeNodeRequest, opts ...grpc.CallOption) (*MergeNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MergeNodeResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_MergeNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) MergeEdge(ctx context.Context, in *MergeEdgeRequest, opts ...grpc.CallOption) (*MergeEdgeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MergeEdgeResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_MergeEdge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_Query_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) KnnSearch(ctx context.Context, in *KnnRequest, opts ...grpc.CallOption) (*KnnResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KnnResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_KnnSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) Bfs(ctx context.Context, in *TraversalRequest, opts ...grpc.CallOption) (*TraversalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TraversalResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_Bfs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) Dijkstra(ctx context.Context, in *TraversalRequest, opts ...grpc.CallOption) (*TraversalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TraversalResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_Dijkstra_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) Diffuse(ctx context.Context, in *DiffusionRequest, opts ...grpc.CallOption) (*DiffusionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiffusionResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_Diffuse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) TriggerSleep(ctx context.Context, in *SleepRequest, opts ...grpc.CallOption) (*SleepResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SleepResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_TriggerSleep_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) InsertSensory(ctx context.Context, in *InsertSensoryRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_InsertSensory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) GetSensory(ctx context.Context, in *NodeIdRequest, opts ...grpc.CallOption) (*SensoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SensoryResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_GetSensory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) Reconstruct(ctx context.Context, in *ReconstructRequest, opts ...grpc.CallOption) (*ReconstructResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReconstructResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_Reconstruct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) DegradeSensory(ctx context.Context, in *NodeIdRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_DegradeSensory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) InvokeZaratustra(ctx context.Context, in *ZaratustraRequest, opts ...grpc.CallOption) (*ZaratustraResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ZaratustraResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_InvokeZaratustra_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) BatchInsertNodes(ctx context.Context, in *BatchInsertNodesRequest, opts ...grpc.CallOption) (*BatchInsertNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchInsertNodesResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_BatchInsertNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) BatchInsertEdges(ctx context.Context, in *BatchInsertEdgesRequest, opts ...grpc.CallOption) (*BatchInsertEdgesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchInsertEdgesResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_BatchInsertEdges_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) RunPageRank(ctx context.Context, in *PageRankRequest, opts ...grpc.CallOption) (*AlgorithmScoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AlgorithmScoreResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_RunPageRank_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) RunLouvain(ctx context.Context, in *LouvainRequest, opts ...grpc.CallOption) (*AlgorithmCommunityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AlgorithmCommunityResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_RunLouvain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) RunLabelProp(ctx context.Context, in *LabelPropRequest, opts ...grpc.CallOption) (*AlgorithmCommunityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AlgorithmCommunityResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_RunLabelProp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) RunBetweenness(ctx context.Context, in *BetweennessRequest, opts ...grpc.CallOption) (*AlgorithmScoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AlgorithmScoreResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_RunBetweenness_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) RunCloseness(ctx context.Context, in *ClosenessRequest, opts ...grpc.CallOption) (*AlgorithmScoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AlgorithmScoreResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_RunCloseness_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) RunDegreeCentrality(ctx context.Context, in *DegreeCentralityRequest, opts ...grpc.CallOption) (*AlgorithmScoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AlgorithmScoreResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_RunDegreeCentrality_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) RunWCC(ctx context.Context, in *WccRequest, opts ...grpc.CallOption) (*AlgorithmCommunityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AlgorithmCommunityResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_RunWCC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) RunSCC(ctx context.Context, in *SccRequest, opts ...grpc.CallOption) (*AlgorithmCommunityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AlgorithmCommunityResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_RunSCC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) RunAStar(ctx context.Context, in *AStarRequest, opts ...grpc.CallOption) (*AStarResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AStarResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_RunAStar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) RunTriangleCount(ctx context.Context, in *TriangleCountRequest, opts ...grpc.CallOption) (*TriangleCountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriangleCountResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_RunTriangleCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) RunJaccardSimilarity(ctx context.Context, in *JaccardRequest, opts ...grpc.CallOption) (*SimilarityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SimilarityResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_RunJaccardSimilarity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) CreateBackup(ctx context.Context, in *CreateBackupRequest, opts ...grpc.CallOption) (*BackupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BackupResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_CreateBackup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) ListBackups(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListBackupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBackupsResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_ListBackups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) RestoreBackup(ctx context.Context, in *RestoreBackupRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_RestoreBackup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) FullTextSearch(ctx context.Context, in *FullTextSearchRequest, opts ...grpc.CallOption) (*FullTextSearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FullTextSearchResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_FullTextSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) SubscribeCDC(ctx context.Context, in *CdcRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CdcEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NietzscheDB_ServiceDesc.Streams[0], NietzscheDB_SubscribeCDC_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CdcRequest, CdcEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NietzscheDB_SubscribeCDCClient = grpc.ServerStreamingClient[CdcEvent]

func (c *nietzscheDBClient) GetStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NietzscheDBServer is the server API for NietzscheDB service.
// All implementations must embed UnimplementedNietzscheDBServer
// for forward compatibility.
type NietzscheDBServer interface {
	// ── Collection management ──────────────────────────────────────────────
	CreateCollection(context.Context, *CreateCollectionRequest) (*CreateCollectionResponse, error)
	DropCollection(context.Context, *DropCollectionRequest) (*StatusResponse, error)
	ListCollections(context.Context, *Empty) (*ListCollectionsResponse, error)
	// ── Node CRUD ─────────────────────────────────────────────────────────
	InsertNode(context.Context, *InsertNodeRequest) (*NodeResponse, error)
	GetNode(context.Context, *NodeIdRequest) (*NodeResponse, error)
	DeleteNode(context.Context, *NodeIdRequest) (*StatusResponse, error)
	UpdateEnergy(context.Context, *UpdateEnergyRequest) (*StatusResponse, error)
	// ── Edge CRUD ─────────────────────────────────────────────────────────
	InsertEdge(context.Context, *InsertEdgeRequest) (*EdgeResponse, error)
	DeleteEdge(context.Context, *EdgeIdRequest) (*StatusResponse, error)
	// ── MERGE (upsert semantic: get-or-create) ────────────────────────────────────
	MergeNode(context.Context, *MergeNodeRequest) (*MergeNodeResponse, error)
	MergeEdge(context.Context, *MergeEdgeRequest) (*MergeEdgeResponse, error)
	// ── NQL query (Nietzsche Query Language) ─────────────────────────────
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
	// ── Vector search (hyperbolic KNN) ───────────────────────────────────
	KnnSearch(context.Context, *KnnRequest) (*KnnResponse, error)
	// ── Graph traversal ───────────────────────────────────────────────────
	Bfs(context.Context, *TraversalRequest) (*TraversalResponse, error)
	Dijkstra(context.Context, *TraversalRequest) (*TraversalResponse, error)
	// ── Heat-kernel diffusion (Phase 6) ──────────────────────────────────
	Diffuse(context.Context, *DiffusionRequest) (*DiffusionResponse, error)
	// ── Reconsolidation sleep cycle (Phase 8) ────────────────────────────
	TriggerSleep(context.Context, *SleepRequest) (*SleepResponse, error)
	// ── Sensory Compression Layer (Phase 11) ─────────────────────────────
	InsertSensory(context.Context, *InsertSensoryRequest) (*StatusResponse, error)
	GetSensory(context.Context, *NodeIdRequest) (*SensoryResponse, error)
	Reconstruct(context.Context, *ReconstructRequest) (*ReconstructResponse, error)
	DegradeSensory(context.Context, *NodeIdRequest) (*StatusResponse, error)
	// ── Zaratustra — autonomous evolution engine (Phase Z) ───────────────
	InvokeZaratustra(context.Context, *ZaratustraRequest) (*ZaratustraResponse, error)
	// ── Batch CRUD ────────────────────────────────────────────────────────
	BatchInsertNodes(context.Context, *BatchInsertNodesRequest) (*BatchInsertNodesResponse, error)
	BatchInsertEdges(context.Context, *BatchInsertEdgesRequest) (*BatchInsertEdgesResponse, error)
	// ── Graph Algorithms ────────────────────────────────────────────────
	RunPageRank(context.Context, *PageRankRequest) (*AlgorithmScoreResponse, error)
	RunLouvain(context.Context, *LouvainRequest) (*AlgorithmCommunityResponse, error)
	RunLabelProp(context.Context, *LabelPropRequest) (*AlgorithmCommunityResponse, error)
	RunBetweenness(context.Context, *BetweennessRequest) (*AlgorithmScoreResponse, error)
	RunCloseness(context.Context, *ClosenessRequest) (*AlgorithmScoreResponse, error)
	RunDegreeCentrality(context.Context, *DegreeCentralityRequest) (*AlgorithmScoreResponse, error)
	RunWCC(context.Context, *WccRequest) (*AlgorithmCommunityResponse, error)
	RunSCC(context.Context, *SccRequest) (*AlgorithmCommunityResponse, error)
	RunAStar(context.Context, *AStarRequest) (*AStarResponse, error)
	RunTriangleCount(context.Context, *TriangleCountRequest) (*TriangleCountResponse, error)
	RunJaccardSimilarity(context.Context, *JaccardRequest) (*SimilarityResponse, error)
	// ── Backup/Restore ───────────────────────────────────────────────────
	CreateBackup(context.Context, *CreateBackupRequest) (*BackupResponse, error)
	ListBackups(context.Context, *Empty) (*ListBackupsResponse, error)
	RestoreBackup(context.Context, *RestoreBackupRequest) (*StatusResponse, error)
	// ── Full-Text Search ────────────────────────────────────────────────
	FullTextSearch(context.Context, *FullTextSearchRequest) (*FullTextSearchResponse, error)
	// ── Change Data Capture ──────────────────────────────────────────────
	SubscribeCDC(*CdcRequest, grpc.ServerStreamingServer[CdcEvent]) error
	// ── Admin ─────────────────────────────────────────────────────────────
	GetStats(context.Context, *Empty) (*StatsResponse, error)
	HealthCheck(context.Context, *Empty) (*StatusResponse, error)
	mustEmbedUnimplementedNietzscheDBServer()
}

// UnimplementedNietzscheDBServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNietzscheDBServer struct{}

func (UnimplementedNietzscheDBServer) CreateCollection(context.Context, *CreateCollectionRequest) (*CreateCollectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCollection not implemented")
}
func (UnimplementedNietzscheDBServer) DropCollection(context.Context, *DropCollectionRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DropCollection not implemented")
}
func (UnimplementedNietzscheDBServer) ListCollections(context.Context, *Empty) (*ListCollectionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCollections not implemented")
}
func (UnimplementedNietzscheDBServer) InsertNode(context.Context, *InsertNodeRequest) (*NodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InsertNode not implemented")
}
func (UnimplementedNietzscheDBServer) GetNode(context.Context, *NodeIdRequest) (*NodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNode not implemented")
}
func (UnimplementedNietzscheDBServer) DeleteNode(context.Context, *NodeIdRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteNode not implemented")
}
func (UnimplementedNietzscheDBServer) UpdateEnergy(context.Context, *UpdateEnergyRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateEnergy not implemented")
}
func (UnimplementedNietzscheDBServer) InsertEdge(context.Context, *InsertEdgeRequest) (*EdgeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InsertEdge not implemented")
}
func (UnimplementedNietzscheDBServer) DeleteEdge(context.Context, *EdgeIdRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteEdge not implemented")
}
func (UnimplementedNietzscheDBServer) MergeNode(context.Context, *MergeNodeRequest) (*MergeNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MergeNode not implemented")
}
func (UnimplementedNietzscheDBServer) MergeEdge(context.Context, *MergeEdgeRequest) (*MergeEdgeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MergeEdge not implemented")
}
func (UnimplementedNietzscheDBServer) Query(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedNietzscheDBServer) KnnSearch(context.Context, *KnnRequest) (*KnnResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KnnSearch not implemented")
}
func (UnimplementedNietzscheDBServer) Bfs(context.Context, *TraversalRequest) (*TraversalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Bfs not implemented")
}
func (UnimplementedNietzscheDBServer) Dijkstra(context.Context, *TraversalRequest) (*TraversalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Dijkstra not implemented")
}
func (UnimplementedNietzscheDBServer) Diffuse(context.Context, *DiffusionRequest) (*DiffusionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Diffuse not implemented")
}
func (UnimplementedNietzscheDBServer) TriggerSleep(context.Context, *SleepRequest) (*SleepResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerSleep not implemented")
}
func (UnimplementedNietzscheDBServer) InsertSensory(context.Context, *InsertSensoryRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InsertSensory not implemented")
}
func (UnimplementedNietzscheDBServer) GetSensory(context.Context, *NodeIdRequest) (*SensoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSensory not implemented")
}
func (UnimplementedNietzscheDBServer) Reconstruct(context.Context, *ReconstructRequest) (*ReconstructResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Reconstruct not implemented")
}
func (UnimplementedNietzscheDBServer) DegradeSensory(context.Context, *NodeIdRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DegradeSensory not implemented")
}
func (UnimplementedNietzscheDBServer) InvokeZaratustra(context.Context, *ZaratustraRequest) (*ZaratustraResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InvokeZaratustra not implemented")
}
func (UnimplementedNietzscheDBServer) BatchInsertNodes(context.Context, *BatchInsertNodesRequest) (*BatchInsertNodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchInsertNodes not implemented")
}
func (UnimplementedNietzscheDBServer) BatchInsertEdges(context.Context, *BatchInsertEdgesRequest) (*BatchInsertEdgesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchInsertEdges not implemented")
}
func (UnimplementedNietzscheDBServer) RunPageRank(context.Context, *PageRankRequest) (*AlgorithmScoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunPageRank not implemented")
}
func (UnimplementedNietzscheDBServer) RunLouvain(context.Context, *LouvainRequest) (*AlgorithmCommunityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunLouvain not implemented")
}
func (UnimplementedNietzscheDBServer) RunLabelProp(context.Context, *LabelPropRequest) (*AlgorithmCommunityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunLabelProp not implemented")
}
func (UnimplementedNietzscheDBServer) RunBetweenness(context.Context, *BetweennessRequest) (*AlgorithmScoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunBetweenness not implemented")
}
func (UnimplementedNietzscheDBServer) RunCloseness(context.Context, *ClosenessRequest) (*AlgorithmScoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunCloseness not implemented")
}
func (UnimplementedNietzscheDBServer) RunDegreeCentrality(context.Context, *DegreeCentralityRequest) (*AlgorithmScoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunDegreeCentrality not implemented")
}
func (UnimplementedNietzscheDBServer) RunWCC(context.Context, *WccRequest) (*AlgorithmCommunityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunWCC not implemented")
}
func (UnimplementedNietzscheDBServer) RunSCC(context.Context, *SccRequest) (*AlgorithmCommunityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunSCC not implemented")
}
func (UnimplementedNietzscheDBServer) RunAStar(context.Context, *AStarRequest) (*AStarResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunAStar not implemented")
}
func (UnimplementedNietzscheDBServer) RunTriangleCount(context.Context, *TriangleCountRequest) (*TriangleCountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunTriangleCount not implemented")
}
func (UnimplementedNietzscheDBServer) RunJaccardSimilarity(context.Context, *JaccardRequest) (*SimilarityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunJaccardSimilarity not implemented")
}
func (UnimplementedNietzscheDBServer) CreateBackup(context.Context, *CreateBackupRequest) (*BackupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBackup not implemented")
}
func (UnimplementedNietzscheDBServer) ListBackups(context.Context, *Empty) (*ListBackupsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBackups not implemented")
}
func (UnimplementedNietzscheDBServer) RestoreBackup(context.Context, *RestoreBackupRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestoreBackup not implemented")
}
func (UnimplementedNietzscheDBServer) FullTextSearch(context.Context, *FullTextSearchRequest) (*FullTextSearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FullTextSearch not implemented")
}
func (UnimplementedNietzscheDBServer) SubscribeCDC(*CdcRequest, grpc.ServerStreamingServer[CdcEvent]) error {
	return status.Error(codes.Unimplemented, "method SubscribeCDC not implemented")
}
func (UnimplementedNietzscheDBServer) GetStats(context.Context, *Empty) (*StatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedNietzscheDBServer) HealthCheck(context.Context, *Empty) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedNietzscheDBServer) mustEmbedUnimplementedNietzscheDBServer() {}
func (UnimplementedNietzscheDBServer) testEmbeddedByValue()                     {}

// UnsafeNietzscheDBServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NietzscheDBServer will
// result in compilation errors.
type UnsafeNietzscheDBServer interface {
	mustEmbedUnimplementedNietzscheDBServer()
}

func RegisterNietzscheDBServer(s grpc.ServiceRegistrar, srv NietzscheDBServer) {
	// If the following call panics, it indicates UnimplementedNietzscheDBServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NietzscheDB_ServiceDesc, srv)
}

func _NietzscheDB_CreateCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).CreateCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_CreateCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).CreateCollection(ctx, req.(*CreateCollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_DropCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropCollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).DropCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_DropCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).DropCollection(ctx, req.(*DropCollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_ListCollections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).ListCollections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_ListCollections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).ListCollections(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_InsertNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).InsertNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_InsertNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).InsertNode(ctx, req.(*InsertNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_GetNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).GetNode(ctx, req.(*NodeIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_DeleteNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).DeleteNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_DeleteNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).DeleteNode(ctx, req.(*NodeIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_UpdateEnergy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEnergyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).UpdateEnergy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_UpdateEnergy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).UpdateEnergy(ctx, req.(*UpdateEnergyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_InsertEdge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertEdgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).InsertEdge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_InsertEdge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).InsertEdge(ctx, req.(*InsertEdgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_DeleteEdge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EdgeIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).DeleteEdge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_DeleteEdge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).DeleteEdge(ctx, req.(*EdgeIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_MergeNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MergeNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).MergeNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_MergeNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).MergeNode(ctx, req.(*MergeNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_MergeEdge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MergeEdgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).MergeEdge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_MergeEdge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).MergeEdge(ctx, req.(*MergeEdgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_KnnSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KnnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).KnnSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_KnnSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).KnnSearch(ctx, req.(*KnnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_Bfs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TraversalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).Bfs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_Bfs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).Bfs(ctx, req.(*TraversalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_Dijkstra_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TraversalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).Dijkstra(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_Dijkstra_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).Dijkstra(ctx, req.(*TraversalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_Diffuse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiffusionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).Diffuse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_Diffuse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).Diffuse(ctx, req.(*DiffusionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_TriggerSleep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SleepRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).TriggerSleep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_TriggerSleep_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).TriggerSleep(ctx, req.(*SleepRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_InsertSensory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertSensoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).InsertSensory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_InsertSensory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).InsertSensory(ctx, req.(*InsertSensoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_GetSensory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).GetSensory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_GetSensory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).GetSensory(ctx, req.(*NodeIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_Reconstruct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReconstructRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).Reconstruct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_Reconstruct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).Reconstruct(ctx, req.(*ReconstructRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_DegradeSensory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).DegradeSensory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_DegradeSensory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).DegradeSensory(ctx, req.(*NodeIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_InvokeZaratustra_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ZaratustraRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).InvokeZaratustra(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_InvokeZaratustra_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).InvokeZaratustra(ctx, req.(*ZaratustraRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_BatchInsertNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchInsertNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).BatchInsertNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_BatchInsertNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).BatchInsertNodes(ctx, req.(*BatchInsertNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_BatchInsertEdges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchInsertEdgesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).BatchInsertEdges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_BatchInsertEdges_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).BatchInsertEdges(ctx, req.(*BatchInsertEdgesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_RunPageRank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PageRankRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).RunPageRank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_RunPageRank_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).RunPageRank(ctx, req.(*PageRankRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_RunLouvain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LouvainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).RunLouvain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_RunLouvain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).RunLouvain(ctx, req.(*LouvainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_RunLabelProp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LabelPropRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).RunLabelProp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_RunLabelProp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).RunLabelProp(ctx, req.(*LabelPropRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_RunBetweenness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BetweennessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).RunBetweenness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_RunBetweenness_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).RunBetweenness(ctx, req.(*BetweennessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_RunCloseness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClosenessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).RunCloseness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_RunCloseness_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).RunCloseness(ctx, req.(*ClosenessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_RunDegreeCentrality_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DegreeCentralityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).RunDegreeCentrality(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_RunDegreeCentrality_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).RunDegreeCentrality(ctx, req.(*DegreeCentralityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_RunWCC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WccRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).RunWCC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_RunWCC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).RunWCC(ctx, req.(*WccRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_RunSCC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SccRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).RunSCC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_RunSCC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).RunSCC(ctx, req.(*SccRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_RunAStar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AStarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).RunAStar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_RunAStar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).RunAStar(ctx, req.(*AStarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_RunTriangleCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriangleCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).RunTriangleCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_RunTriangleCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).RunTriangleCount(ctx, req.(*TriangleCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_RunJaccardSimilarity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JaccardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).RunJaccardSimilarity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_RunJaccardSimilarity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).RunJaccardSimilarity(ctx, req.(*JaccardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_CreateBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).CreateBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_CreateBackup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).CreateBackup(ctx, req.(*CreateBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_ListBackups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).ListBackups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_ListBackups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).ListBackups(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_RestoreBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).RestoreBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_RestoreBackup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).RestoreBackup(ctx, req.(*RestoreBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_FullTextSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FullTextSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).FullTextSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_FullTextSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).FullTextSearch(ctx, req.(*FullTextSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_SubscribeCDC_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CdcRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NietzscheDBServer).SubscribeCDC(m, &grpc.GenericServerStream[CdcRequest, CdcEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NietzscheDB_SubscribeCDCServer = grpc.ServerStreamingServer[CdcEvent]

func _NietzscheDB_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).GetStats(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).HealthCheck(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// NietzscheDB_ServiceDesc is the grpc.ServiceDesc for NietzscheDB service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NietzscheDB_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nietzsche.NietzscheDB",
	HandlerType: (*NietzscheDBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCollection",
			Handler:    _NietzscheDB_CreateCollection_Handler,
		},
		{
			MethodName: "DropCollection",
			Handler:    _NietzscheDB_DropCollection_Handler,
		},
		{
			MethodName: "ListCollections",
			Handler:    _NietzscheDB_ListCollections_Handler,
		},
		{
			MethodName: "InsertNode",
			Handler:    _NietzscheDB_InsertNode_Handler,
		},
		{
			MethodName: "GetNode",
			Handler:    _NietzscheDB_GetNode_Handler,
		},
		{
			MethodName: "DeleteNode",
			Handler:    _NietzscheDB_DeleteNode_Handler,
		},
		{
			MethodName: "UpdateEnergy",
			Handler:    _NietzscheDB_UpdateEnergy_Handler,
		},
		{
			MethodName: "InsertEdge",
			Handler:    _NietzscheDB_InsertEdge_Handler,
		},
		{
			MethodName: "DeleteEdge",
			Handler:    _NietzscheDB_DeleteEdge_Handler,
		},
		{
			MethodName: "MergeNode",
			Handler:    _NietzscheDB_MergeNode_Handler,
		},
		{
			MethodName: "MergeEdge",
			Handler:    _NietzscheDB_MergeEdge_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _NietzscheDB_Query_Handler,
		},
		{
			MethodName: "KnnSearch",
			Handler:    _NietzscheDB_KnnSearch_Handler,
		},
		{
			MethodName: "Bfs",
			Handler:    _NietzscheDB_Bfs_Handler,
		},
		{
			MethodName: "Dijkstra",
			Handler:    _NietzscheDB_Dijkstra_Handler,
		},
		{
			MethodName: "Diffuse",
			Handler:    _NietzscheDB_Diffuse_Handler,
		},
		{
			MethodName: "TriggerSleep",
			Handler:    _NietzscheDB_TriggerSleep_Handler,
		},
		{
			MethodName: "InsertSensory",
			Handler:    _NietzscheDB_InsertSensory_Handler,
		},
		{
			MethodName: "GetSensory",
			Handler:    _NietzscheDB_GetSensory_Handler,
		},
		{
			MethodName: "Reconstruct",
			Handler:    _NietzscheDB_Reconstruct_Handler,
		},
		{
			MethodName: "DegradeSensory",
			Handler:    _NietzscheDB_DegradeSensory_Handler,
		},
		{
			MethodName: "InvokeZaratustra",
			Handler:    _NietzscheDB_InvokeZaratustra_Handler,
		},
		{
			MethodName: "BatchInsertNodes",
			Handler:    _NietzscheDB_BatchInsertNodes_Handler,
		},
		{
			MethodName: "BatchInsertEdges",
			Handler:    _NietzscheDB_BatchInsertEdges_Handler,
		},
		{
			MethodName: "RunPageRank",
			Handler:    _NietzscheDB_RunPageRank_Handler,
		},
		{
			MethodName: "RunLouvain",
			Handler:    _NietzscheDB_RunLouvain_Handler,
		},
		{
			MethodName: "RunLabelProp",
			Handler:    _NietzscheDB_RunLabelProp_Handler,
		},
		{
			MethodName: "RunBetweenness",
			Handler:    _NietzscheDB_RunBetweenness_Handler,
		},
		{
			MethodName: "RunCloseness",
			Handler:    _NietzscheDB_RunCloseness_Handler,
		},
		{
			MethodName: "RunDegreeCentrality",
			Handler:    _NietzscheDB_RunDegreeCentrality_Handler,
		},
		{
			MethodName: "RunWCC",
			Handler:    _NietzscheDB_RunWCC_Handler,
		},
		{
			MethodName: "RunSCC",
			Handler:    _NietzscheDB_RunSCC_Handler,
		},
		{
			MethodName: "RunAStar",
			Handler:    _NietzscheDB_RunAStar_Handler,
		},
		{
			MethodName: "RunTriangleCount",
			Handler:    _NietzscheDB_RunTriangleCount_Handler,
		},
		{
			MethodName: "RunJaccardSimilarity",
			Handler:    _NietzscheDB_RunJaccardSimilarity_Handler,
		},
		{
			MethodName: "CreateBackup",
			Handler:    _NietzscheDB_CreateBackup_Handler,
		},
		{
			MethodName: "ListBackups",
			Handler:    _NietzscheDB_ListBackups_Handler,
		},
		{
			MethodName: "RestoreBackup",
			Handler:    _NietzscheDB_RestoreBackup_Handler,
		},
		{
			MethodName: "FullTextSearch",
			Handler:    _NietzscheDB_FullTextSearch_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _NietzscheDB_GetStats_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _NietzscheDB_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeCDC",
			Handler:       _NietzscheDB_SubscribeCDC_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/nietzsche.proto",
}
