// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.5
// source: proto/nietzsche.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NietzscheDB_CreateCollection_FullMethodName = "/nietzsche.NietzscheDB/CreateCollection"
	NietzscheDB_DropCollection_FullMethodName   = "/nietzsche.NietzscheDB/DropCollection"
	NietzscheDB_ListCollections_FullMethodName  = "/nietzsche.NietzscheDB/ListCollections"
	NietzscheDB_InsertNode_FullMethodName       = "/nietzsche.NietzscheDB/InsertNode"
	NietzscheDB_GetNode_FullMethodName          = "/nietzsche.NietzscheDB/GetNode"
	NietzscheDB_DeleteNode_FullMethodName       = "/nietzsche.NietzscheDB/DeleteNode"
	NietzscheDB_UpdateEnergy_FullMethodName     = "/nietzsche.NietzscheDB/UpdateEnergy"
	NietzscheDB_InsertEdge_FullMethodName       = "/nietzsche.NietzscheDB/InsertEdge"
	NietzscheDB_DeleteEdge_FullMethodName       = "/nietzsche.NietzscheDB/DeleteEdge"
	NietzscheDB_MergeNode_FullMethodName        = "/nietzsche.NietzscheDB/MergeNode"
	NietzscheDB_MergeEdge_FullMethodName        = "/nietzsche.NietzscheDB/MergeEdge"
	NietzscheDB_Query_FullMethodName            = "/nietzsche.NietzscheDB/Query"
	NietzscheDB_KnnSearch_FullMethodName        = "/nietzsche.NietzscheDB/KnnSearch"
	NietzscheDB_Bfs_FullMethodName              = "/nietzsche.NietzscheDB/Bfs"
	NietzscheDB_Dijkstra_FullMethodName         = "/nietzsche.NietzscheDB/Dijkstra"
	NietzscheDB_Diffuse_FullMethodName          = "/nietzsche.NietzscheDB/Diffuse"
	NietzscheDB_TriggerSleep_FullMethodName     = "/nietzsche.NietzscheDB/TriggerSleep"
	NietzscheDB_InsertSensory_FullMethodName    = "/nietzsche.NietzscheDB/InsertSensory"
	NietzscheDB_GetSensory_FullMethodName       = "/nietzsche.NietzscheDB/GetSensory"
	NietzscheDB_Reconstruct_FullMethodName      = "/nietzsche.NietzscheDB/Reconstruct"
	NietzscheDB_DegradeSensory_FullMethodName   = "/nietzsche.NietzscheDB/DegradeSensory"
	NietzscheDB_InvokeZaratustra_FullMethodName = "/nietzsche.NietzscheDB/InvokeZaratustra"
	NietzscheDB_GetStats_FullMethodName         = "/nietzsche.NietzscheDB/GetStats"
	NietzscheDB_HealthCheck_FullMethodName      = "/nietzsche.NietzscheDB/HealthCheck"
)

// NietzscheDBClient is the client API for NietzscheDB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NietzscheDBClient interface {
	// ── Collection management ──────────────────────────────────────────────
	CreateCollection(ctx context.Context, in *CreateCollectionRequest, opts ...grpc.CallOption) (*CreateCollectionResponse, error)
	DropCollection(ctx context.Context, in *DropCollectionRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	ListCollections(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListCollectionsResponse, error)
	// ── Node CRUD ─────────────────────────────────────────────────────────
	InsertNode(ctx context.Context, in *InsertNodeRequest, opts ...grpc.CallOption) (*NodeResponse, error)
	GetNode(ctx context.Context, in *NodeIdRequest, opts ...grpc.CallOption) (*NodeResponse, error)
	DeleteNode(ctx context.Context, in *NodeIdRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	UpdateEnergy(ctx context.Context, in *UpdateEnergyRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// ── Edge CRUD ─────────────────────────────────────────────────────────
	InsertEdge(ctx context.Context, in *InsertEdgeRequest, opts ...grpc.CallOption) (*EdgeResponse, error)
	DeleteEdge(ctx context.Context, in *EdgeIdRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// ── MERGE (upsert semantic: get-or-create) ────────────────────────────────────
	MergeNode(ctx context.Context, in *MergeNodeRequest, opts ...grpc.CallOption) (*MergeNodeResponse, error)
	MergeEdge(ctx context.Context, in *MergeEdgeRequest, opts ...grpc.CallOption) (*MergeEdgeResponse, error)
	// ── NQL query (Nietzsche Query Language) ─────────────────────────────
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	// ── Vector search (hyperbolic KNN) ───────────────────────────────────
	KnnSearch(ctx context.Context, in *KnnRequest, opts ...grpc.CallOption) (*KnnResponse, error)
	// ── Graph traversal ───────────────────────────────────────────────────
	Bfs(ctx context.Context, in *TraversalRequest, opts ...grpc.CallOption) (*TraversalResponse, error)
	Dijkstra(ctx context.Context, in *TraversalRequest, opts ...grpc.CallOption) (*TraversalResponse, error)
	// ── Heat-kernel diffusion (Phase 6) ──────────────────────────────────
	Diffuse(ctx context.Context, in *DiffusionRequest, opts ...grpc.CallOption) (*DiffusionResponse, error)
	// ── Reconsolidation sleep cycle (Phase 8) ────────────────────────────
	TriggerSleep(ctx context.Context, in *SleepRequest, opts ...grpc.CallOption) (*SleepResponse, error)
	// ── Sensory Compression Layer (Phase 11) ─────────────────────────────
	InsertSensory(ctx context.Context, in *InsertSensoryRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	GetSensory(ctx context.Context, in *NodeIdRequest, opts ...grpc.CallOption) (*SensoryResponse, error)
	Reconstruct(ctx context.Context, in *ReconstructRequest, opts ...grpc.CallOption) (*ReconstructResponse, error)
	DegradeSensory(ctx context.Context, in *NodeIdRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// ── Zaratustra — autonomous evolution engine (Phase Z) ───────────────
	InvokeZaratustra(ctx context.Context, in *ZaratustraRequest, opts ...grpc.CallOption) (*ZaratustraResponse, error)
	// ── Admin ─────────────────────────────────────────────────────────────
	GetStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatsResponse, error)
	HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResponse, error)
}

type nietzscheDBClient struct {
	cc grpc.ClientConnInterface
}

func NewNietzscheDBClient(cc grpc.ClientConnInterface) NietzscheDBClient {
	return &nietzscheDBClient{cc}
}

func (c *nietzscheDBClient) CreateCollection(ctx context.Context, in *CreateCollectionRequest, opts ...grpc.CallOption) (*CreateCollectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCollectionResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_CreateCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) DropCollection(ctx context.Context, in *DropCollectionRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_DropCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) ListCollections(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListCollectionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCollectionsResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_ListCollections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) InsertNode(ctx context.Context, in *InsertNodeRequest, opts ...grpc.CallOption) (*NodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_InsertNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) GetNode(ctx context.Context, in *NodeIdRequest, opts ...grpc.CallOption) (*NodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_GetNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) DeleteNode(ctx context.Context, in *NodeIdRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_DeleteNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) UpdateEnergy(ctx context.Context, in *UpdateEnergyRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_UpdateEnergy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) InsertEdge(ctx context.Context, in *InsertEdgeRequest, opts ...grpc.CallOption) (*EdgeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EdgeResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_InsertEdge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) DeleteEdge(ctx context.Context, in *EdgeIdRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_DeleteEdge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) MergeNode(ctx context.Context, in *MergeNodeRequest, opts ...grpc.CallOption) (*MergeNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MergeNodeResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_MergeNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) MergeEdge(ctx context.Context, in *MergeEdgeRequest, opts ...grpc.CallOption) (*MergeEdgeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MergeEdgeResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_MergeEdge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_Query_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) KnnSearch(ctx context.Context, in *KnnRequest, opts ...grpc.CallOption) (*KnnResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KnnResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_KnnSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) Bfs(ctx context.Context, in *TraversalRequest, opts ...grpc.CallOption) (*TraversalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TraversalResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_Bfs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) Dijkstra(ctx context.Context, in *TraversalRequest, opts ...grpc.CallOption) (*TraversalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TraversalResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_Dijkstra_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) Diffuse(ctx context.Context, in *DiffusionRequest, opts ...grpc.CallOption) (*DiffusionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiffusionResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_Diffuse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) TriggerSleep(ctx context.Context, in *SleepRequest, opts ...grpc.CallOption) (*SleepResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SleepResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_TriggerSleep_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) InsertSensory(ctx context.Context, in *InsertSensoryRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_InsertSensory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) GetSensory(ctx context.Context, in *NodeIdRequest, opts ...grpc.CallOption) (*SensoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SensoryResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_GetSensory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) Reconstruct(ctx context.Context, in *ReconstructRequest, opts ...grpc.CallOption) (*ReconstructResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReconstructResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_Reconstruct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) DegradeSensory(ctx context.Context, in *NodeIdRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_DegradeSensory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) InvokeZaratustra(ctx context.Context, in *ZaratustraRequest, opts ...grpc.CallOption) (*ZaratustraResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ZaratustraResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_InvokeZaratustra_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) GetStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nietzscheDBClient) HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, NietzscheDB_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NietzscheDBServer is the server API for NietzscheDB service.
// All implementations must embed UnimplementedNietzscheDBServer
// for forward compatibility.
type NietzscheDBServer interface {
	// ── Collection management ──────────────────────────────────────────────
	CreateCollection(context.Context, *CreateCollectionRequest) (*CreateCollectionResponse, error)
	DropCollection(context.Context, *DropCollectionRequest) (*StatusResponse, error)
	ListCollections(context.Context, *Empty) (*ListCollectionsResponse, error)
	// ── Node CRUD ─────────────────────────────────────────────────────────
	InsertNode(context.Context, *InsertNodeRequest) (*NodeResponse, error)
	GetNode(context.Context, *NodeIdRequest) (*NodeResponse, error)
	DeleteNode(context.Context, *NodeIdRequest) (*StatusResponse, error)
	UpdateEnergy(context.Context, *UpdateEnergyRequest) (*StatusResponse, error)
	// ── Edge CRUD ─────────────────────────────────────────────────────────
	InsertEdge(context.Context, *InsertEdgeRequest) (*EdgeResponse, error)
	DeleteEdge(context.Context, *EdgeIdRequest) (*StatusResponse, error)
	// ── MERGE (upsert semantic: get-or-create) ────────────────────────────────────
	MergeNode(context.Context, *MergeNodeRequest) (*MergeNodeResponse, error)
	MergeEdge(context.Context, *MergeEdgeRequest) (*MergeEdgeResponse, error)
	// ── NQL query (Nietzsche Query Language) ─────────────────────────────
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
	// ── Vector search (hyperbolic KNN) ───────────────────────────────────
	KnnSearch(context.Context, *KnnRequest) (*KnnResponse, error)
	// ── Graph traversal ───────────────────────────────────────────────────
	Bfs(context.Context, *TraversalRequest) (*TraversalResponse, error)
	Dijkstra(context.Context, *TraversalRequest) (*TraversalResponse, error)
	// ── Heat-kernel diffusion (Phase 6) ──────────────────────────────────
	Diffuse(context.Context, *DiffusionRequest) (*DiffusionResponse, error)
	// ── Reconsolidation sleep cycle (Phase 8) ────────────────────────────
	TriggerSleep(context.Context, *SleepRequest) (*SleepResponse, error)
	// ── Sensory Compression Layer (Phase 11) ─────────────────────────────
	InsertSensory(context.Context, *InsertSensoryRequest) (*StatusResponse, error)
	GetSensory(context.Context, *NodeIdRequest) (*SensoryResponse, error)
	Reconstruct(context.Context, *ReconstructRequest) (*ReconstructResponse, error)
	DegradeSensory(context.Context, *NodeIdRequest) (*StatusResponse, error)
	// ── Zaratustra — autonomous evolution engine (Phase Z) ───────────────
	InvokeZaratustra(context.Context, *ZaratustraRequest) (*ZaratustraResponse, error)
	// ── Admin ─────────────────────────────────────────────────────────────
	GetStats(context.Context, *Empty) (*StatsResponse, error)
	HealthCheck(context.Context, *Empty) (*StatusResponse, error)
	mustEmbedUnimplementedNietzscheDBServer()
}

// UnimplementedNietzscheDBServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNietzscheDBServer struct{}

func (UnimplementedNietzscheDBServer) CreateCollection(context.Context, *CreateCollectionRequest) (*CreateCollectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCollection not implemented")
}
func (UnimplementedNietzscheDBServer) DropCollection(context.Context, *DropCollectionRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DropCollection not implemented")
}
func (UnimplementedNietzscheDBServer) ListCollections(context.Context, *Empty) (*ListCollectionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCollections not implemented")
}
func (UnimplementedNietzscheDBServer) InsertNode(context.Context, *InsertNodeRequest) (*NodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InsertNode not implemented")
}
func (UnimplementedNietzscheDBServer) GetNode(context.Context, *NodeIdRequest) (*NodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNode not implemented")
}
func (UnimplementedNietzscheDBServer) DeleteNode(context.Context, *NodeIdRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteNode not implemented")
}
func (UnimplementedNietzscheDBServer) UpdateEnergy(context.Context, *UpdateEnergyRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateEnergy not implemented")
}
func (UnimplementedNietzscheDBServer) InsertEdge(context.Context, *InsertEdgeRequest) (*EdgeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InsertEdge not implemented")
}
func (UnimplementedNietzscheDBServer) DeleteEdge(context.Context, *EdgeIdRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteEdge not implemented")
}
func (UnimplementedNietzscheDBServer) MergeNode(context.Context, *MergeNodeRequest) (*MergeNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MergeNode not implemented")
}
func (UnimplementedNietzscheDBServer) MergeEdge(context.Context, *MergeEdgeRequest) (*MergeEdgeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MergeEdge not implemented")
}
func (UnimplementedNietzscheDBServer) Query(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedNietzscheDBServer) KnnSearch(context.Context, *KnnRequest) (*KnnResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KnnSearch not implemented")
}
func (UnimplementedNietzscheDBServer) Bfs(context.Context, *TraversalRequest) (*TraversalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Bfs not implemented")
}
func (UnimplementedNietzscheDBServer) Dijkstra(context.Context, *TraversalRequest) (*TraversalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Dijkstra not implemented")
}
func (UnimplementedNietzscheDBServer) Diffuse(context.Context, *DiffusionRequest) (*DiffusionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Diffuse not implemented")
}
func (UnimplementedNietzscheDBServer) TriggerSleep(context.Context, *SleepRequest) (*SleepResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerSleep not implemented")
}
func (UnimplementedNietzscheDBServer) InsertSensory(context.Context, *InsertSensoryRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InsertSensory not implemented")
}
func (UnimplementedNietzscheDBServer) GetSensory(context.Context, *NodeIdRequest) (*SensoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSensory not implemented")
}
func (UnimplementedNietzscheDBServer) Reconstruct(context.Context, *ReconstructRequest) (*ReconstructResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Reconstruct not implemented")
}
func (UnimplementedNietzscheDBServer) DegradeSensory(context.Context, *NodeIdRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DegradeSensory not implemented")
}
func (UnimplementedNietzscheDBServer) InvokeZaratustra(context.Context, *ZaratustraRequest) (*ZaratustraResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InvokeZaratustra not implemented")
}
func (UnimplementedNietzscheDBServer) GetStats(context.Context, *Empty) (*StatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedNietzscheDBServer) HealthCheck(context.Context, *Empty) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedNietzscheDBServer) mustEmbedUnimplementedNietzscheDBServer() {}
func (UnimplementedNietzscheDBServer) testEmbeddedByValue()                     {}

// UnsafeNietzscheDBServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NietzscheDBServer will
// result in compilation errors.
type UnsafeNietzscheDBServer interface {
	mustEmbedUnimplementedNietzscheDBServer()
}

func RegisterNietzscheDBServer(s grpc.ServiceRegistrar, srv NietzscheDBServer) {
	// If the following call panics, it indicates UnimplementedNietzscheDBServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NietzscheDB_ServiceDesc, srv)
}

func _NietzscheDB_CreateCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).CreateCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_CreateCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).CreateCollection(ctx, req.(*CreateCollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_DropCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropCollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).DropCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_DropCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).DropCollection(ctx, req.(*DropCollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_ListCollections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).ListCollections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_ListCollections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).ListCollections(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_InsertNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).InsertNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_InsertNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).InsertNode(ctx, req.(*InsertNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_GetNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).GetNode(ctx, req.(*NodeIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_DeleteNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).DeleteNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_DeleteNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).DeleteNode(ctx, req.(*NodeIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_UpdateEnergy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEnergyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).UpdateEnergy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_UpdateEnergy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).UpdateEnergy(ctx, req.(*UpdateEnergyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_InsertEdge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertEdgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).InsertEdge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_InsertEdge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).InsertEdge(ctx, req.(*InsertEdgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_DeleteEdge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EdgeIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).DeleteEdge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_DeleteEdge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).DeleteEdge(ctx, req.(*EdgeIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_MergeNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MergeNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).MergeNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_MergeNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).MergeNode(ctx, req.(*MergeNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_MergeEdge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MergeEdgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).MergeEdge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_MergeEdge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).MergeEdge(ctx, req.(*MergeEdgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_KnnSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KnnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).KnnSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_KnnSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).KnnSearch(ctx, req.(*KnnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_Bfs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TraversalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).Bfs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_Bfs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).Bfs(ctx, req.(*TraversalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_Dijkstra_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TraversalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).Dijkstra(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_Dijkstra_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).Dijkstra(ctx, req.(*TraversalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_Diffuse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiffusionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).Diffuse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_Diffuse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).Diffuse(ctx, req.(*DiffusionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_TriggerSleep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SleepRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).TriggerSleep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_TriggerSleep_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).TriggerSleep(ctx, req.(*SleepRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_InsertSensory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertSensoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).InsertSensory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_InsertSensory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).InsertSensory(ctx, req.(*InsertSensoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_GetSensory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).GetSensory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_GetSensory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).GetSensory(ctx, req.(*NodeIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_Reconstruct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReconstructRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).Reconstruct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_Reconstruct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).Reconstruct(ctx, req.(*ReconstructRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_DegradeSensory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).DegradeSensory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_DegradeSensory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).DegradeSensory(ctx, req.(*NodeIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_InvokeZaratustra_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ZaratustraRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).InvokeZaratustra(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_InvokeZaratustra_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).InvokeZaratustra(ctx, req.(*ZaratustraRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).GetStats(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NietzscheDB_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NietzscheDBServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NietzscheDB_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NietzscheDBServer).HealthCheck(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// NietzscheDB_ServiceDesc is the grpc.ServiceDesc for NietzscheDB service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NietzscheDB_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nietzsche.NietzscheDB",
	HandlerType: (*NietzscheDBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCollection",
			Handler:    _NietzscheDB_CreateCollection_Handler,
		},
		{
			MethodName: "DropCollection",
			Handler:    _NietzscheDB_DropCollection_Handler,
		},
		{
			MethodName: "ListCollections",
			Handler:    _NietzscheDB_ListCollections_Handler,
		},
		{
			MethodName: "InsertNode",
			Handler:    _NietzscheDB_InsertNode_Handler,
		},
		{
			MethodName: "GetNode",
			Handler:    _NietzscheDB_GetNode_Handler,
		},
		{
			MethodName: "DeleteNode",
			Handler:    _NietzscheDB_DeleteNode_Handler,
		},
		{
			MethodName: "UpdateEnergy",
			Handler:    _NietzscheDB_UpdateEnergy_Handler,
		},
		{
			MethodName: "InsertEdge",
			Handler:    _NietzscheDB_InsertEdge_Handler,
		},
		{
			MethodName: "DeleteEdge",
			Handler:    _NietzscheDB_DeleteEdge_Handler,
		},
		{
			MethodName: "MergeNode",
			Handler:    _NietzscheDB_MergeNode_Handler,
		},
		{
			MethodName: "MergeEdge",
			Handler:    _NietzscheDB_MergeEdge_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _NietzscheDB_Query_Handler,
		},
		{
			MethodName: "KnnSearch",
			Handler:    _NietzscheDB_KnnSearch_Handler,
		},
		{
			MethodName: "Bfs",
			Handler:    _NietzscheDB_Bfs_Handler,
		},
		{
			MethodName: "Dijkstra",
			Handler:    _NietzscheDB_Dijkstra_Handler,
		},
		{
			MethodName: "Diffuse",
			Handler:    _NietzscheDB_Diffuse_Handler,
		},
		{
			MethodName: "TriggerSleep",
			Handler:    _NietzscheDB_TriggerSleep_Handler,
		},
		{
			MethodName: "InsertSensory",
			Handler:    _NietzscheDB_InsertSensory_Handler,
		},
		{
			MethodName: "GetSensory",
			Handler:    _NietzscheDB_GetSensory_Handler,
		},
		{
			MethodName: "Reconstruct",
			Handler:    _NietzscheDB_Reconstruct_Handler,
		},
		{
			MethodName: "DegradeSensory",
			Handler:    _NietzscheDB_DegradeSensory_Handler,
		},
		{
			MethodName: "InvokeZaratustra",
			Handler:    _NietzscheDB_InvokeZaratustra_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _NietzscheDB_GetStats_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _NietzscheDB_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/nietzsche.proto",
}
