#!/usr/bin/env python3
"""NietzscheDB Graph Curator Agent — autonomous graph organization powered by Claude.

This agent connects to NietzscheDB and autonomously:
- Analyzes graph structure (PageRank, Louvain, WCC, betweenness)
- Finds and merges duplicate nodes
- Creates missing semantic edges between related concepts
- Prunes dead/disconnected nodes
- Optimizes embeddings via sleep cycles
- Reports findings and actions taken

Usage:
    # Autonomous mode — agent decides what to do
    python agent.py

    # Directed mode — give it a specific task
    python agent.py "Find duplicate nodes in tech_galaxies and merge them"

    # Single collection
    python agent.py --collection tech_galaxies "Analyze the graph structure"

    # Dry run (report only, no mutations)
    python agent.py --dry-run "What needs to be cleaned up?"
"""

from __future__ import annotations

import argparse
import json
import sys
import os

import anthropic
from rich.console import Console
from rich.panel import Panel
from rich.markdown import Markdown

sys.path.insert(0, os.path.dirname(__file__))

from config import CLAUDE_MODEL, MAX_TURNS, DEFAULT_COLLECTIONS
from tools import TOOL_DEFINITIONS, execute_tool

console = Console()

# ── System prompt ─────────────────────────────────────────────────────────

SYSTEM_PROMPT = """\
You are the NietzscheDB Graph Curator — an autonomous agent that maintains and \
optimizes hyperbolic knowledge graphs stored in NietzscheDB.

## Your Database
NietzscheDB stores knowledge as nodes in a Poincaré ball (hyperbolic space). \
The magnitude of a node's coordinates encodes its depth/specificity:
- ~0.1 = root/abstract concepts (e.g., "Science", "Philosophy")
- ~0.3-0.5 = mid-level topics (e.g., "Machine Learning", "Ethics")
- ~0.7-0.9 = specific/leaf nodes (e.g., "Gradient Descent", "Trolley Problem")

Edges connect related nodes: Association (semantic link), Hierarchical (parent-child), \
LSystemGenerated (auto-generated by the L-System engine).

Node types: Semantic (knowledge), Episodic (events/memories), Concept (abstract), DreamSnapshot.

## Your Capabilities
You have full access to the database via tools. You can:
1. **Analyze**: Run PageRank, Louvain, WCC, betweenness to understand graph structure
2. **Search**: Query nodes via NQL, full-text search, or KNN vector search
3. **Organize**: Insert/delete nodes and edges, merge duplicates, update energy
4. **Optimize**: Trigger sleep cycles (reconsolidation), reap expired nodes
5. **Protect**: Create backups before major changes

## Your Workflow
1. Start by listing collections and getting an overview
2. Pick a collection to analyze (or follow user instructions)
3. Run graph algorithms to understand the structure
4. Identify problems (orphans, duplicates, missing links, low-energy clusters)
5. Report findings clearly
6. Take action (or recommend actions if in dry-run mode)

## Rules
- ALWAYS create a backup before making significant mutations (>5 changes)
- NEVER delete nodes with energy > 0.5 without explicit user approval
- Prefer merging duplicates over deleting either copy
- When creating edges, use Association for semantic relationships, Hierarchical for parent-child
- Report what you find and what you did in clear, structured format
- Be efficient — don't query the same data twice
- For 128-dim vectors, generate random Poincaré coords using small magnitude (~0.3) when needed

## NQL Quick Reference
- `MATCH (n:Semantic) RETURN n LIMIT 20` — get semantic nodes
- `MATCH (n)-[e]->(m) RETURN n,m LIMIT 50` — get edges
- `MATCH (n:Concept) WHERE n.energy > 0.5 RETURN n` — filter by energy
- Node types in MATCH: Episodic, Semantic, Concept, DreamSnapshot
"""

DRY_RUN_ADDENDUM = """

## DRY RUN MODE
You are in dry-run mode. Do NOT make any mutations (no insert, delete, merge, sleep, etc.).
Only analyze and report what SHOULD be done. Describe your recommendations clearly.
"""


def run_agent(
    task: str | None = None,
    collections: list[str] | None = None,
    dry_run: bool = False,
    max_turns: int = MAX_TURNS,
    verbose: bool = False,
) -> str:
    """Run the curator agent and return the final response."""

    client = anthropic.Anthropic()

    system = SYSTEM_PROMPT
    if dry_run:
        system += DRY_RUN_ADDENDUM

    if task is None:
        cols = ", ".join(collections or DEFAULT_COLLECTIONS)
        task = (
            f"Analyze the NietzscheDB collections [{cols}] and perform maintenance:\n"
            "1. List all collections and their sizes\n"
            "2. For each collection, run PageRank and Louvain to understand structure\n"
            "3. Check for disconnected components (WCC)\n"
            "4. Identify problems: orphan nodes, potential duplicates, missing cross-links\n"
            "5. Take corrective actions (or recommend them if dry-run)\n"
            "6. Summarize your findings and actions in a clear report"
        )
    elif collections and len(collections) == 1:
        task = f"[Working on collection: {collections[0]}]\n\n{task}"

    # Filter tools in dry-run mode
    tools = TOOL_DEFINITIONS
    if dry_run:
        mutation_tools = {
            "insert_node", "insert_edge", "delete_node", "delete_edge",
            "merge_node", "update_energy", "reap_expired", "trigger_sleep",
        }
        tools = [t for t in tools if t["name"] not in mutation_tools]

    messages = [{"role": "user", "content": task}]

    console.print(Panel(f"[bold cyan]NietzscheDB Graph Curator[/bold cyan]\n"
                        f"Model: {CLAUDE_MODEL} | Max turns: {max_turns} | "
                        f"Dry run: {dry_run}",
                        title="Agent Started"))
    console.print(f"[dim]Task: {task[:200]}{'...' if len(task) > 200 else ''}[/dim]\n")

    final_text = ""

    for turn in range(max_turns):
        if verbose:
            console.print(f"[dim]── Turn {turn + 1}/{max_turns} ──[/dim]")

        response = client.messages.create(
            model=CLAUDE_MODEL,
            max_tokens=8192,
            system=system,
            tools=tools,
            messages=messages,
        )

        # Process response
        assistant_content = response.content
        tool_results = []

        for block in assistant_content:
            if block.type == "text":
                final_text = block.text
                if verbose:
                    console.print(Markdown(block.text))

            elif block.type == "tool_use":
                tool_name = block.name
                tool_input = block.input
                console.print(
                    f"  [yellow]▶ {tool_name}[/yellow]"
                    f"({_summarize_input(tool_input)})"
                )

                result_str = execute_tool(tool_name, tool_input)

                # Show truncated result
                if verbose:
                    preview = result_str[:300] + "..." if len(result_str) > 300 else result_str
                    console.print(f"  [green]◀ {preview}[/green]")

                tool_results.append({
                    "type": "tool_result",
                    "tool_use_id": block.id,
                    "content": result_str,
                })

        # If no tool calls, agent is done
        if response.stop_reason == "end_turn":
            console.print(Panel("[bold green]Agent finished[/bold green]"))
            if final_text:
                console.print(Markdown(final_text))
            break

        # Continue conversation with tool results
        messages.append({"role": "assistant", "content": assistant_content})
        messages.append({"role": "user", "content": tool_results})

    else:
        console.print("[red]Agent reached max turns limit[/red]")

    return final_text


def _summarize_input(inp: dict) -> str:
    """One-line summary of tool input for logging."""
    parts = []
    for k, v in inp.items():
        if k == "coords":
            parts.append(f"coords=[{len(v)}D]")
        elif k == "nql":
            parts.append(f'nql="{v[:60]}"')
        elif isinstance(v, str):
            parts.append(f'{k}="{v}"')
        elif isinstance(v, (int, float)):
            parts.append(f"{k}={v}")
        elif isinstance(v, dict):
            parts.append(f"{k}={{...}}")
    return ", ".join(parts)


def main():
    parser = argparse.ArgumentParser(description="NietzscheDB Graph Curator Agent")
    parser.add_argument("task", nargs="?", default=None, help="Task for the agent")
    parser.add_argument("--collection", "-c", type=str, default=None,
                        help="Focus on a single collection")
    parser.add_argument("--collections", type=str, default=None,
                        help="Comma-separated collection list")
    parser.add_argument("--dry-run", "-n", action="store_true",
                        help="Report only, no mutations")
    parser.add_argument("--max-turns", "-t", type=int, default=MAX_TURNS,
                        help=f"Max agent turns (default {MAX_TURNS})")
    parser.add_argument("--verbose", "-v", action="store_true",
                        help="Show full agent reasoning")
    args = parser.parse_args()

    collections = DEFAULT_COLLECTIONS
    if args.collection:
        collections = [args.collection]
    elif args.collections:
        collections = args.collections.split(",")

    run_agent(
        task=args.task,
        collections=collections,
        dry_run=args.dry_run,
        max_turns=args.max_turns,
        verbose=args.verbose,
    )


if __name__ == "__main__":
    main()
