#!/bin/bash
# ─────────────────────────────────────────────────────────────────────────────
# Build the React dashboard and embed it into html.rs (nietzsche-server).
# Run from the NietzscheDB repo root:  ./scripts/build-dashboard.sh
# ─────────────────────────────────────────────────────────────────────────────
set -e

export PATH=/usr/local/go/bin:/usr/local/bin:/usr/bin:/bin
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DASHBOARD_DIR="$REPO_ROOT/dashboard"
HTML_RS="$REPO_ROOT/crates/nietzsche-server/src/html.rs"
DIST_HTML="$DASHBOARD_DIR/dist/index.html"

echo "=== [1/4] Installing dashboard deps ==="
cd "$DASHBOARD_DIR"
npm install --legacy-peer-deps 2>&1 | tail -3

echo "=== [2/4] Building React dashboard (single-file) ==="
npm run build 2>&1 | tail -8

if [ ! -f "$DIST_HTML" ]; then
    echo "ERROR: dist/index.html not found after build"
    exit 1
fi

echo "=== [3/4] Updating html.rs with include_str! ==="
cat > "$HTML_RS" << 'RUST'
// AUTO-GENERATED by scripts/build-dashboard.sh — DO NOT EDIT MANUALLY
// To update: run ./scripts/build-dashboard.sh then rebuild nietzsche-server.

pub const DASHBOARD_HTML: &str =
    include_str!("../../../dashboard/dist/index.html");
RUST

echo "html.rs -> include_str!(dashboard/dist/index.html)"

echo "=== [4/4] Rebuilding nietzsche-server ==="
cd "$REPO_ROOT"
export CXX=/usr/local/bin/g++
export CC=/usr/local/bin/gcc
cargo build --release --bin nietzsche-server 2>&1 | grep -E 'Compiling nietzsche-server|Finished|^error'
echo "SERVER_BUILD_EXIT:$?"
