// Copyright (C) 2025-2026 Jose R F Junior <petweofc@gmail.com>
// SPDX-License-Identifier: AGPL-3.0-or-later

package nietzsche

// InsertNodeOpts configures a node insertion into NietzscheDB.
type InsertNodeOpts struct {
	ID         string      // UUIDv4; auto-generated by server if empty
	Coords     []float64   // Poincaré ball embedding coordinates
	Content    interface{} // arbitrary payload, JSON-marshalled automatically
	NodeType   string      // "Semantic"|"Episodic"|"Concept"|"DreamSnapshot"; "" → "Semantic"
	Energy     float32     // node energy level; 0 → server default (1.0)
	Collection string      // target collection; "" → "default"
}

// MergeNodeOpts configures a MERGE (upsert) node operation.
// Semantics: find a node matching node_type + match_keys, or create one.
type MergeNodeOpts struct {
	Collection  string                 // "" → "default"
	NodeType    string                 // label to match (e.g. "Topic", "Person")
	MatchKeys   map[string]interface{} // content keys to match on (e.g. {"name": "value"})
	OnCreateSet map[string]interface{} // properties to set if creating new node
	OnMatchSet  map[string]interface{} // properties to update if node exists
	Coords      []float64              // optional Poincaré embedding for new node
	Energy      float32                // energy for new node; 0 → server default (1.0)
}

// MergeNodeResult contains the result of a MERGE node operation.
type MergeNodeResult struct {
	Created bool       // true if a new node was created
	NodeID  string     // UUID of the matched or created node
	Node    NodeResult // full node data
}

// MergeEdgeOpts configures a MERGE (upsert) edge operation.
type MergeEdgeOpts struct {
	Collection  string                 // "" → "default"
	FromNodeID  string                 // source node UUID
	ToNodeID    string                 // target node UUID
	EdgeType    string                 // "Association"|"Hierarchical"|etc.
	OnCreateSet map[string]interface{} // properties for new edge
	OnMatchSet  map[string]interface{} // properties to update on existing edge
}

// MergeEdgeResult contains the result of a MERGE edge operation.
type MergeEdgeResult struct {
	Created bool   // true if a new edge was created
	EdgeID  string // UUID of the matched or created edge
}

// InsertEdgeOpts configures an edge insertion.
type InsertEdgeOpts struct {
	ID         string  // UUIDv4; auto-generated by server if empty
	From       string  // source node UUID
	To         string  // target node UUID
	EdgeType   string  // "Association"|"Hierarchical"|"LSystemGenerated"|"Pruned"
	Weight     float64 // edge weight; 0 → server default (1.0)
	Collection string  // "" → "default"
}

// TraversalOpts configures BFS or Dijkstra traversals.
type TraversalOpts struct {
	MaxDepth  uint32  // max hops (BFS) or max settled nodes (Dijkstra); 0 → default 10
	MaxNodes  uint32  // hard cap on visited nodes; 0 → default 1000
	MaxCost   float64 // Dijkstra only: max cumulative distance; 0 → unlimited
	EnergyMin float32 // skip nodes below this energy level
}

// SleepOpts configures the Riemannian reconsolidation sleep cycle.
type SleepOpts struct {
	Noise              float64 // perturbation magnitude; 0 → default 0.02
	AdamSteps          uint32  // Adam optimiser steps per node; 0 → default 10
	AdamLr             float64 // Adam learning rate; 0 → default 5e-3
	HausdorffThreshold float32 // max |ΔH| to commit; 0 → default 0.15
	RngSeed            uint64  // 0 → non-deterministic
	Collection         string  // "" → "default"
}

// DiffuseOpts configures heat-kernel diffusion.
type DiffuseOpts struct {
	TValues    []float64 // diffusion times; nil → [0.1, 1.0, 10.0]
	KChebyshev uint32    // Chebyshev polynomial order; 0 → default 10
	Collection string    // "" → "default"
}

// ZaratustraOpts configures the autonomous evolution engine.
type ZaratustraOpts struct {
	Alpha      float32 // propagation coefficient; 0 → server default
	Decay      float32 // energy decay rate; 0 → server default
	Cycles     uint32  // complete cycles to run; 0 → 1
	Collection string  // "" → "default"
}

// CollectionConfig specifies parameters for creating a new collection.
type CollectionConfig struct {
	Name   string // required, collection name
	Dim    uint32 // vector dimension; 0 → server default (3072)
	Metric string // "cosine"|"euclidean"|"poincare"; "" → "cosine"
}

// InsertSensoryOpts configures sensory data insertion.
type InsertSensoryOpts struct {
	NodeID         string    // existing node UUID to attach sensory data to
	Modality       string    // "text"|"audio"|"image"|"fused"
	Latent         []float32 // pre-compressed Euclidean vector
	OriginalShape  []byte    // JSON-encoded shape metadata
	OriginalBytes  uint32    // size of the original raw data
	EncoderVersion uint32    // encoder version for decoder compatibility
	ModalityMeta   []byte    // JSON metadata (e.g. sample_rate, duration_ms)
	Collection     string    // "" → "default"
}

// ── Result types ────────────────────────────────────────────────────────────

// NodeResult represents a node returned by NietzscheDB.
type NodeResult struct {
	Found          bool
	ID             string
	Embedding      []float64
	Energy         float32
	Depth          float32
	HausdorffLocal float32
	CreatedAt      int64
	Content        map[string]interface{}
	NodeType       string
}

// KnnResult represents a single nearest-neighbour result.
type KnnResult struct {
	ID       string
	Distance float64
}

// SleepResult contains metrics from a reconsolidation sleep cycle.
type SleepResult struct {
	HausdorffBefore float32
	HausdorffAfter  float32
	HausdorffDelta  float32
	Committed       bool
	NodesPerturbed  uint32
	SnapshotNodes   uint32
}

// CollectionInfo describes a single collection.
type CollectionInfo struct {
	Name      string
	Dim       uint32
	Metric    string
	NodeCount uint64
	EdgeCount uint64
}

// Stats contains global database statistics.
type Stats struct {
	NodeCount    uint64
	EdgeCount    uint64
	Version      string
	SensoryCount uint64
}

// QueryResult aggregates all possible outputs from an NQL query.
type QueryResult struct {
	Nodes      []NodeResult
	NodePairs  []NodePairResult
	PathIDs    []string
	ScalarRows []map[string]interface{}
	Explain    string
	Error      string
}

// NodePairResult represents a pair of nodes from an edge query.
type NodePairResult struct {
	From NodeResult
	To   NodeResult
}

// DiffusionScale holds diffusion results for a single time value.
type DiffusionScale struct {
	T       float64
	NodeIDs []string
	Scores  []float64
}

// SensoryResult describes the sensory data attached to a node.
type SensoryResult struct {
	Found                 bool
	NodeID                string
	Modality              string
	Dim                   uint32
	QuantLevel            string // "f32"|"f16"|"int8"|"pq"|"gone"
	ReconstructionQuality float32
	CompressionRatio      float32
	EncoderVersion        uint32
	ByteSize              uint32
}

// ReconstructResult contains the reconstructed sensory latent vector.
type ReconstructResult struct {
	Found         bool
	NodeID        string
	Latent        []float32
	Modality      string
	Quality       float32
	OriginalShape []byte
}

// ZaratustraResult contains full metrics from the Zaratustra evolution cycle.
type ZaratustraResult struct {
	// Will to Power
	NodesUpdated     uint64
	MeanEnergyBefore float32
	MeanEnergyAfter  float32
	TotalEnergyDelta float32
	// Eternal Recurrence
	EchoesCreated uint64
	EchoesEvicted uint64
	TotalEchoes   uint64
	// Übermensch
	EliteCount      uint64
	EliteThreshold  float32
	MeanEliteEnergy float32
	MeanBaseEnergy  float32
	EliteNodeIDs    []string
	// Timing
	DurationMs uint64
	CyclesRun  uint32
}
