use nietzsche_graph::{AdjacencyIndex, GraphStorage};
use nietzsche_hyp_ops::poincare_distance;

use crate::attention_cycle::{EcanConfig, EcanCycle};
use crate::attention_economy::{AttentionConfig, AttentionReport};
use crate::curiosity_engine::CuriosityConfig;
use crate::hebbian::{HebbianConfig, HebbianReport, HebbianState, run_hebbian_tick};
use crate::thermodynamics::{
    ThermodynamicReport, ThermodynamicState, ThermodynamicsConfig,
    run_thermodynamic_cycle,
};
use crate::gravity::{GravityConfig, GravityNode, GravityReport, GravityState, run_gravity_tick};
use crate::dirty_set::{DirtySet, DirtySetConfig, ScanDecision};
use crate::shatter::{ShatterDaemon, build_shatter_plan, build_shatter_config, run_shatter_scan};
use crate::self_healing::SelfHealingDaemon;
use crate::axiom_registry::AxiomRegistry;
use crate::centroid_guardian::CentroidGuardian;
use crate::hyperbolic_health::{HyperbolicHealth, HyperbolicHealthMonitor};
use crate::config::AgencyConfig;
use crate::circuit_breaker::EnergyCircuitBreaker;
use crate::daemons::{AgencyDaemon, CoherenceDaemon, DaemonReport, EntropyDaemon, EvolutionDaemon, GapDaemon, LTDDaemon, NezhmetdinovDaemon, NiilistaGcDaemon, NeuralThresholdDaemon};
use crate::desire::{DesireEngine, DesireSignal};
use crate::error::AgencyError;
use crate::event_bus::{AgencyEvent, AgencyEventBus, SectorId};
use crate::identity::ObserverIdentity;
use crate::maturity::{MaturityConfig, NodeClass, NodeMaturityInput, evaluate_maturity};
use crate::observer::{HealthReport, MetaObserver};
use crate::reactor::{AgencyIntent, AgencyReactor};

use std::collections::{hash_map::DefaultHasher, HashSet};
use std::hash::{Hash, Hasher};
use uuid::Uuid;

/// Full tick report from the agency engine.
#[derive(Debug)]
pub struct AgencyTickReport {
    pub daemon_reports: Vec<DaemonReport>,
    pub health_report: Option<HealthReport>,
    /// Intents produced by the reactor — the server should execute these
    /// under a write lock after the tick completes.
    pub intents: Vec<AgencyIntent>,
    /// Desire signals generated by the Motor de Desejo.
    pub desires: Vec<DesireSignal>,
    /// CentroidGuardian update result (None if no active nodes).
    pub centroid_update: Option<crate::centroid_guardian::CentroidUpdate>,
    /// Number of nodes promoted Active → Mature (Sagração).
    pub promotions: usize,
    /// Number of nodes demoted Mature → Active.
    pub demotions: usize,
    /// Hyperbolic health snapshot (None if not yet time for a check).
    pub hyperbolic_health: Option<HyperbolicHealth>,
    /// ECAN attention report (None if interval-gated or disabled).
    pub attention_report: Option<AttentionReport>,
    /// Hebbian LTP report (None if disabled or no winning bids).
    pub hebbian_report: Option<HebbianReport>,
    /// Cognitive thermodynamics report (None if interval-gated or disabled).
    pub thermodynamic_report: Option<ThermodynamicReport>,
    /// Semantic gravity field report (None if interval-gated or disabled).
    pub gravity_report: Option<GravityReport>,
    /// Shatter protocol report (None if interval-gated or disabled).
    pub shatter_report: Option<crate::shatter::ShatterReport>,
    pub healing_report: Option<crate::self_healing::HealingReport>,
    pub duration_ms: u64,
}

/// Top-level agency engine that orchestrates daemons, observer, reactor,
/// desire engine, and event bus.
///
/// Create once and call [`tick`](AgencyEngine::tick) periodically from a
/// background Tokio task. The engine holds only configuration and lightweight
/// state (observer tick counter + event buffer + reactor cooldowns).
///
/// ## Tick protocol
///
/// 1. Tick each daemon sequentially (read-only graph scan + analysis + emit events)
/// 2. Tick the observer (drain events + aggregate metrics + maybe produce HealthReport)
/// 3. Tick the reactor (drain events + produce intents)
/// 4. Process knowledge gaps through the Motor de Desejo
/// 5. Update Observer Identity meta-node with latest health
/// 6. Return combined `AgencyTickReport` with intents + desires
pub struct AgencyEngine {
    pub config: AgencyConfig,
    bus: AgencyEventBus,
    daemons: Vec<Box<dyn AgencyDaemon>>,
    observer: MetaObserver,
    reactor: AgencyReactor,
    desire_engine: DesireEngine,
    /// Collects gap events from daemons for the desire engine.
    gap_rx: tokio::sync::broadcast::Receiver<AgencyEvent>,
    circuit_breaker: EnergyCircuitBreaker,
    /// HashSet of actions currently on cooldown (O(1) access).
    pub active_reflex_cooldowns: HashSet<Uuid>,
    /// CentroidGuardian — the Geometric Self (Phase IX).
    centroid_guardian: CentroidGuardian,
    /// AxiomRegistry — civilizational memory (Phase IX).
    axiom_registry: AxiomRegistry,
    /// HyperbolicHealthMonitor — geometric health (Phase X).
    hyp_health_monitor: HyperbolicHealthMonitor,
    /// ECAN — Economic Attention Network (Phase XII).
    ecan_cycle: EcanCycle,
    /// Hebbian LTP — structural plasticity (Phase XII.5).
    hebbian_state: HebbianState,
    /// Cognitive Thermodynamics — temperature, entropy, free energy (Phase XIII).
    thermo_state: ThermodynamicState,
    /// Previous phase state for phase transition detection.
    last_phase: Option<crate::thermodynamics::PhaseState>,
    /// Semantic Gravity — gravitational field between concepts (Phase XIV).
    gravity_state: GravityState,
    /// DirtySet — adaptive sampling for O(Δ) scans (Phase XV).
    dirty_set: std::sync::Arc<DirtySet>,
    dirty_config: DirtySetConfig,
    /// Shatter Protocol tick counter (Phase XVI).
    shatter_tick: u64,
}

impl AgencyEngine {
    pub fn new(config: AgencyConfig) -> Self {
        let bus = AgencyEventBus::new(256);
        let observer = MetaObserver::new(&bus);
        let ppo_engine = nietzsche_rl::PpoEngine::new(nietzsche_rl::PpoConfig {
            model_name: config.ppo_model_name.clone(),
            ..Default::default()
        });
        let reactor = AgencyReactor::new(&bus, Some(ppo_engine));
        let desire_engine = DesireEngine::new();
        let gap_rx = bus.subscribe();
        Self {
            daemons: vec![
                Box::new(EntropyDaemon),
                Box::new(GapDaemon),
                Box::new(CoherenceDaemon),
                Box::new(NiilistaGcDaemon),
                Box::new(LTDDaemon),
                Box::new(EvolutionDaemon),
                Box::new(NeuralThresholdDaemon::new(&config.gnn_model_name)),
                Box::new(NezhmetdinovDaemon::new()),
                Box::new(ShatterDaemon),
                Box::new(SelfHealingDaemon),
            ],
            observer,
            reactor,
            desire_engine,
            gap_rx,
            bus,
            circuit_breaker: EnergyCircuitBreaker {
                max_active_reflexes: config.circuit_breaker_max_actions,
                energy_sum_threshold: config.circuit_breaker_energy_sum_threshold,
            },
            active_reflex_cooldowns: HashSet::new(),
            centroid_guardian: CentroidGuardian::new(config.centroid_dim),
            axiom_registry: AxiomRegistry::new(),
            hyp_health_monitor: HyperbolicHealthMonitor::new(),
            ecan_cycle: EcanCycle::new(),
            hebbian_state: HebbianState::new(),
            thermo_state: ThermodynamicState::new(),
            last_phase: None,
            gravity_state: GravityState::new(),
            dirty_set: std::sync::Arc::new(DirtySet::new()),
            dirty_config: DirtySetConfig {
                full_scan_ratio: config.dirty_full_scan_ratio,
                stability_sample: config.dirty_stability_sample,
                enabled: config.dirty_enabled,
            },
            shatter_tick: 0,
            config,
        }
    }

    /// Create from environment variables.
    pub fn from_env() -> Self {
        Self::new(AgencyConfig::from_env())
    }

    /// Initialize the CentroidGuardian from persisted storage.
    ///
    /// Call this once after construction when `GraphStorage` is available.
    /// Restores the centroid position and epoch from CF_META.
    pub fn init_centroid_from_storage(&mut self, storage: &GraphStorage) {
        self.centroid_guardian = CentroidGuardian::from_storage(storage, self.config.centroid_dim);
    }

    /// Access the CentroidGuardian (read-only).
    pub fn centroid_guardian(&self) -> &CentroidGuardian {
        &self.centroid_guardian
    }

    /// Access the CentroidGuardian (mutable, for unfreeze after sleep).
    pub fn centroid_guardian_mut(&mut self) -> &mut CentroidGuardian {
        &mut self.centroid_guardian
    }

    /// Access the AxiomRegistry (read-only).
    pub fn axiom_registry(&self) -> &AxiomRegistry {
        &self.axiom_registry
    }

    /// Access the HyperbolicHealthMonitor (read-only).
    pub fn hyp_health_monitor(&self) -> &HyperbolicHealthMonitor {
        &self.hyp_health_monitor
    }

    /// Process maturity promotions and demotions (Selection → Memory).
    ///
    /// Scans active nodes, evaluates maturity via the integrated score
    /// `M_i = V_i · log(1+S_i) · C_i · exp(-Var(angle_i))`, and:
    ///
    /// - **Active → Mature**: Register in AxiomRegistry (Sagração)
    /// - **Mature → Active**: Deregister from AxiomRegistry (demotion)
    ///
    /// Guards:
    /// - **Drift veto**: Skips all promotions when CentroidGuardian is frozen
    /// - **Semantic deduplication**: Skips if embedding is within ε of an existing axiom
    fn process_promotions(
        &self,
        storage: &GraphStorage,
    ) -> (usize, usize) {
        // Drift veto: block all promotions when the identity is unstable
        let frozen = self.centroid_guardian.is_frozen();

        let maturity_config = MaturityConfig {
            promote_threshold: self.config.maturity_promote_threshold,
            demote_threshold: self.config.maturity_demote_threshold,
        };

        let dim = self.centroid_guardian.dim();
        let mut promotions = 0usize;
        let mut demotions = 0usize;
        let mut scanned = 0usize;

        for result in storage.iter_nodes_meta() {
            let meta = match result {
                Ok(m) => m,
                Err(_) => continue,
            };

            // Skip phantom and expired
            if meta.is_phantom {
                continue;
            }

            scanned += 1;
            if scanned > self.config.maturity_max_eval {
                break;
            }

            // Load embedding (f32 → f64, ITEM C)
            let emb = match storage.get_embedding(&meta.id) {
                Ok(Some(e)) if e.dim == dim => e,
                _ => continue,
            };
            let coords_f64: Vec<f64> = emb.coords.iter().map(|&x| x as f64).collect();

            // Determine previous class
            let is_currently_axiom = self.axiom_registry.is_axiom(meta.id);
            let previous_class = if meta.energy <= 0.0 {
                NodeClass::Latent
            } else if is_currently_axiom {
                NodeClass::Mature
            } else {
                NodeClass::Active
            };

            // Skip latent nodes entirely
            if previous_class == NodeClass::Latent {
                continue;
            }

            // Build input — approximate stability and angular_variance from available data
            // Stability: use energy as proxy (high energy = stable idea)
            // Angular variance: use (1 - depth) as proxy (deep nodes = more variance)
            let vitality = meta.energy.max(0.0) as f64;
            let stability = (meta.energy.max(0.0) * 2.0) as f64; // scaled energy proxy
            let angular_variance = (meta.depth.max(0.0) * 0.5) as f64; // depth-based proxy

            let input = NodeMaturityInput {
                node_id: meta.id,
                embedding: coords_f64.clone(),
                vitality,
                stability,
                angular_variance,
                previous_class,
            };

            let result = evaluate_maturity(&input, &self.centroid_guardian, &maturity_config);

            match result.transition {
                Some((NodeClass::Active, NodeClass::Mature)) => {
                    if frozen {
                        tracing::debug!(
                            node_id = %meta.id,
                            score = result.score,
                            "promotion blocked: centroid drift veto active"
                        );
                        continue;
                    }

                    // Semantic deduplication: check if too close to existing axiom
                    if self.is_duplicate_axiom(storage, &coords_f64) {
                        tracing::debug!(
                            node_id = %meta.id,
                            "promotion skipped: semantic duplicate (within ε of existing axiom)"
                        );
                        continue;
                    }

                    // Sagração — register the axiom
                    match self.axiom_registry.register(
                        storage,
                        meta.id,
                        &coords_f64,
                        result.score,
                        &self.centroid_guardian,
                    ) {
                        Ok(_) => {
                            promotions += 1;
                        }
                        Err(e) => {
                            tracing::warn!(node_id = %meta.id, error = %e, "axiom registration failed");
                        }
                    }
                }
                Some((NodeClass::Mature, NodeClass::Active)) => {
                    // Demotion — deregister from axiom
                    match self.axiom_registry.deregister(storage, meta.id) {
                        Ok(_) => {
                            demotions += 1;
                        }
                        Err(e) => {
                            tracing::warn!(node_id = %meta.id, error = %e, "axiom deregistration failed");
                        }
                    }
                }
                _ => {}
            }
        }

        if promotions > 0 || demotions > 0 {
            tracing::info!(
                promotions,
                demotions,
                axiom_count = self.axiom_registry.count(),
                frozen,
                "maturity evaluation complete"
            );
        }

        (promotions, demotions)
    }

    /// Check if an embedding is within ε of any existing axiom (semantic dedup).
    fn is_duplicate_axiom(&self, storage: &GraphStorage, embedding: &[f64]) -> bool {
        let epsilon = self.config.axiom_dedup_epsilon;

        // Iterate L1 cache — O(N) but axiom count is typically small (< 1000)
        for entry in self.axiom_registry.iter_cache() {
            let d = poincare_distance(embedding, &entry.value().embedding_snapshot);
            if d < epsilon {
                return true;
            }
        }

        false
    }

    /// Run one tick of the full agency cycle.
    ///
    /// Takes only shared references to storage and adjacency — the agency
    /// engine is completely **read-only** and never mutates the graph
    /// (except for CF_META writes which are atomic at RocksDB level).
    /// Any structural mutations are expressed as `AgencyIntent`s for the
    /// server to execute under a write lock.
    pub fn tick(
        &mut self,
        storage: &GraphStorage,
        adjacency: &AdjacencyIndex,
    ) -> Result<AgencyTickReport, AgencyError> {
        let t0 = std::time::Instant::now();

        // 1. Tick each daemon
        let mut daemon_reports = Vec::with_capacity(self.daemons.len());
        for daemon in &self.daemons {
            let report = daemon.tick(storage, adjacency, &self.bus, &self.config)?;
            tracing::debug!(
                daemon = daemon.name(),
                events = report.events_emitted,
                scanned = report.nodes_scanned,
                us = report.duration_us,
                "daemon tick"
            );
            daemon_reports.push(report);
        }

        // 2. Tick observer (may emit HealthReport + WakeUp events)
        let health_report = self.observer.tick(storage, adjacency, &self.bus, &self.config)?;

        // 3. Tick reactor (converts events → intents)
        let mut intents = self.reactor.tick(&self.config);

        if !intents.is_empty() {
            tracing::info!(
                intent_count = intents.len(),
                "agency reactor produced intents"
            );
        }

        // 4. Collect gap events and feed to desire engine
        let gaps = self.drain_gap_events();
        let desires = self.desire_engine.process_gaps(&gaps, storage, &self.bus, &self.config)?;

        // 5. Desire → Dream: trigger dreams for high-priority desires
        let dream_intents = self.generate_dream_intents(&desires, storage);
        intents.extend(dream_intents);

        // 6. Update Observer Identity with latest health (if report was generated)
        if let Some(ref health) = health_report {
            if let Err(e) = ObserverIdentity::update_from_health(storage, health) {
                tracing::warn!(error = %e, "failed to update observer identity");
            }
        }

        // 7. Tick CentroidGuardian — update the Geometric Self (Phase IX)
        let centroid_update = match self.centroid_guardian.tick(storage, &self.bus, &self.config) {
            Ok(update) => update,
            Err(e) => {
                tracing::warn!(error = %e, "CentroidGuardian tick failed");
                None
            }
        };

        // 8. Process maturity promotions: Selection → Memory (Phase IX)
        let (promotions, demotions) = self.process_promotions(storage);

        // 9. Era snapshot (periodic civilizational checkpoint)
        if self.config.axiom_era_snapshot_interval > 0
            && self.centroid_guardian.epoch() % self.config.axiom_era_snapshot_interval == 0
            && self.centroid_guardian.epoch() > 0
        {
            if let Err(e) = self.axiom_registry.snapshot_era(
                storage,
                self.centroid_guardian.epoch(),
                self.centroid_guardian.current_centroid(),
            ) {
                tracing::warn!(error = %e, "era snapshot failed");
            }
        }

        // 10. Tick HyperbolicHealthMonitor (Phase X, frequency-gated)
        let hyperbolic_health = self.hyp_health_monitor.tick(
            storage,
            &self.centroid_guardian,
            &self.bus,
            &self.config,
        );

        // 11. Tick Code-as-Data (Reflexive Actions)
        if let Ok(report) = crate::code_as_data::scan_activatable_actions(storage) {
            if !report.activated.is_empty() {
                // Check safety via circuit breaker
                match self.circuit_breaker.check_safety(storage, report.activated.len()) {
                    Ok(true) => {
                        for action in report.activated {
                            intents.push(AgencyIntent::ExecuteNQL {
                                node_id: action.node_id,
                                nql: action.nql,
                                description: action.description,
                            });
                            // Add to memory-active cooldown set
                            self.active_reflex_cooldowns.insert(action.node_id);
                        }
                    }
                    Ok(false) => {
                        tracing::warn!("agency tick: reflexive actions blocked by circuit breaker");
                    }
                    Err(e) => tracing::error!(error = ?e, "circuit breaker check failed"),
                }
            }
            // Tick cooldowns using optimized HashSet (avoids O(N) scan)
            if !self.active_reflex_cooldowns.is_empty() {
                match crate::code_as_data::tick_cooldowns_optimized(storage, &self.active_reflex_cooldowns) {
                    Ok(finished) => {
                        for id in finished {
                            self.active_reflex_cooldowns.remove(&id);
                        }
                    }
                    Err(e) => tracing::error!(error = ?e, "failed to tick reflexes cooldowns"),
                }
            }
        }

        // 12. Tick ECAN — Economic Attention Network (Phase XII)
        let attention_report = if self.config.ecan_interval > 0 {
            let ecan_config = build_ecan_config(&self.config);
            match self.ecan_cycle.tick(storage, adjacency, &ecan_config) {
                Ok(report) => report,
                Err(e) => {
                    tracing::warn!(error = %e, "ECAN cycle failed");
                    None
                }
            }
        } else {
            None
        };

        // 12b. Mark ECAN energy delta nodes as dirty for adaptive sampling
        if let Some(ref att) = attention_report {
            for (id, _) in &att.energy_deltas {
                self.dirty_set.mark(*id);
            }
        }

        // 13. Hebbian LTP — structural plasticity (Phase XII.5)
        //     Uses ECAN winning bids to strengthen co-activated edges.
        let hebbian_report = if self.config.hebbian_enabled {
            if let Some(ref att_report) = attention_report {
                // Extract winning bids: top_receivers tells us who received,
                // but we need the actual winning bids. We reconstruct from
                // energy_deltas (receivers with positive delta were bid winners).
                // For a cleaner integration, we use the report's energy_deltas
                // as a proxy for co-activation strength.
                let proxy_bids: Vec<crate::attention_economy::AttentionBid> = att_report
                    .energy_deltas
                    .iter()
                    .filter(|(_, d)| *d > 0.0)
                    .flat_map(|(target, d)| {
                        // Create a synthetic bid representing the attention received
                        att_report.top_receivers.iter().take(5).map(move |(src, _)| {
                            crate::attention_economy::AttentionBid {
                                source: *src,
                                target: *target,
                                value: *d,
                            }
                        })
                    })
                    .collect();

                let hebb_config = build_hebbian_config(&self.config);
                let report = run_hebbian_tick(&mut self.hebbian_state, &proxy_bids, &hebb_config);

                // Mark Hebbian endpoints dirty
                for delta in &report.deltas {
                    self.dirty_set.mark(delta.source);
                    self.dirty_set.mark(delta.target);
                }

                // Emit HebbianPotentiation event if edges were strengthened
                if report.potentiated > 0 {
                    self.bus.publish(crate::event_bus::AgencyEvent::HebbianPotentiation {
                        edges_potentiated: report.potentiated,
                        total_delta: report.total_delta,
                        active_traces: report.active_traces,
                    });
                    // Convert hebbian deltas to intents
                    for delta in &report.deltas {
                        intents.push(AgencyIntent::HebbianLTP {
                            from_id: delta.source,
                            to_id: delta.target,
                            weight_delta: delta.weight_delta,
                            trace: delta.trace,
                        });
                    }
                }

                Some(report)
            } else {
                None
            }
        } else {
            None
        };

        // 14. Cognitive Thermodynamics — temperature, entropy, free energy (Phase XIII)
        let thermodynamic_report = if self.config.thermo_interval > 0 {
            let thermo_tick = self.thermo_state.ema_temperature(); // use for gating
            let _ = thermo_tick; // silence unused warning

            // Collect energy samples from participating nodes
            let mut energies = Vec::new();
            let mut edge_energies = Vec::new();
            let mut scanned = 0usize;
            let max_scan = self.config.ecan_max_scan.max(5_000);

            for result in storage.iter_nodes_meta() {
                let meta = match result {
                    Ok(m) => m,
                    Err(_) => continue,
                };
                if meta.is_phantom {
                    continue;
                }
                energies.push(meta.energy);

                // Sample edge energy pairs for heat flow computation
                if self.config.thermo_enable_heat_flow {
                    let neighbours = adjacency.neighbors_out(&meta.id);
                    for nid in neighbours.iter().take(3) { // sample ≤3 edges per node
                        if let Ok(Some(n_meta)) = storage.get_node_meta(nid) {
                            edge_energies.push((meta.id, *nid, meta.energy, n_meta.energy));
                        }
                    }
                }

                scanned += 1;
                if scanned >= max_scan {
                    break;
                }
            }

            let thermo_config = build_thermo_config(&self.config);
            let report = run_thermodynamic_cycle(
                &mut self.thermo_state,
                &energies,
                &edge_energies,
                &thermo_config,
            );

            // Detect phase transitions and emit events
            if let Some(prev_phase) = self.last_phase {
                if prev_phase != report.phase {
                    self.bus.publish(crate::event_bus::AgencyEvent::PhaseTransition {
                        from_phase: format!("{}", prev_phase),
                        to_phase: format!("{}", report.phase),
                        temperature: report.temperature,
                        entropy: report.entropy,
                        free_energy: report.free_energy,
                    });
                    tracing::info!(
                        from = %prev_phase,
                        to = %report.phase,
                        T = format!("{:.4}", report.temperature),
                        "cognitive phase transition detected"
                    );
                }
            }
            self.last_phase = Some(report.phase);

            // Convert heat flows to energy adjustment intents + mark dirty
            for flow in &report.heat_flows {
                self.dirty_set.mark(flow.from);
                self.dirty_set.mark(flow.to);
                intents.push(AgencyIntent::HeatFlow {
                    from_id: flow.from,
                    to_id: flow.to,
                    amount: flow.amount,
                });
            }

            Some(report)
        } else {
            None
        };

        // 15. Semantic Gravity — gravitational field between concepts (Phase XIV)
        let gravity_report = if self.config.gravity_enabled {
            // Collect gravity nodes: need id, energy, degree, embedding
            // First pass: collect candidates from meta iterator (cheap)
            let mut candidates: Vec<(Uuid, f32, usize)> = Vec::new();
            let max_gravity_nodes = (self.config.gravity_max_pairs as f64).sqrt() as usize + 10;
            let mut g_scanned = 0usize;

            for result in storage.iter_nodes_meta() {
                let meta = match result {
                    Ok(m) => m,
                    Err(_) => continue,
                };
                if meta.is_phantom || meta.energy < 1e-6 {
                    continue;
                }
                let degree = adjacency.degree_out(&meta.id) + adjacency.degree_in(&meta.id);
                candidates.push((meta.id, meta.energy, degree));
                g_scanned += 1;
                if g_scanned >= max_gravity_nodes {
                    break;
                }
            }

            // Second pass: fetch embeddings for candidates (read from CF_EMBEDDINGS)
            let mut gravity_nodes = Vec::with_capacity(candidates.len());
            for (id, energy, degree) in &candidates {
                if let Ok(Some(emb)) = storage.get_embedding(id) {
                    if !emb.coords.is_empty() {
                        let embedding: Vec<f64> = emb.coords.iter().map(|&c| c as f64).collect();
                        gravity_nodes.push(GravityNode {
                            id: *id,
                            energy: *energy,
                            degree: *degree,
                            embedding,
                        });
                    }
                }
            }

            let gravity_config = build_gravity_config(&self.config);
            let report = run_gravity_tick(&mut self.gravity_state, &gravity_nodes, &gravity_config);

            // Convert gravity pulls to intents (if enabled) + mark dirty
            if let Some(ref r) = report {
                for pull in &r.pulls {
                    self.dirty_set.mark(pull.node_id);
                    intents.push(AgencyIntent::GravityPull {
                        well_id: pull.well_id,
                        node_id: pull.node_id,
                        amount: pull.amount,
                    });
                }
            }

            report
        } else {
            None
        };

        // 16. Shatter Protocol — split super-nodes into context avatars (Phase XVI)
        self.shatter_tick += 1;
        let shatter_report = {
            let shatter_config = build_shatter_config(&self.config);
            match run_shatter_scan(storage, adjacency, &shatter_config, self.shatter_tick) {
                Some((report, plans)) => {
                    // Convert each plan into a ShatterNode intent
                    for plan in plans {
                        intents.push(AgencyIntent::ShatterNode {
                            node_id: plan.candidate.node_id,
                            avatars: plan.avatars,
                        });
                    }
                    Some(report)
                }
                None => None,
            }
        };

        // 17. Self-Healing — extract healing report from daemon reports (Phase XIX)
        let healing_report = daemon_reports.iter()
            .find(|r| r.daemon_name == "self_healing")
            .and_then(|_| {
                // The actual report is emitted via event bus; extract from latest event
                None // Populated by dashboard from event bus
            });

        Ok(AgencyTickReport {
            daemon_reports,
            health_report,
            intents,
            desires,
            centroid_update,
            promotions,
            demotions,
            hyperbolic_health,
            attention_report,
            hebbian_report,
            thermodynamic_report,
            gravity_report,
            shatter_report,
            healing_report,
            duration_ms: t0.elapsed().as_millis() as u64,
        })
    }

    /// Drain KnowledgeGap events from the bus for the desire engine.
    fn drain_gap_events(&mut self) -> Vec<(SectorId, f64, (f32, f32))> {
        let mut gaps = Vec::new();
        loop {
            match self.gap_rx.try_recv() {
                Ok(AgencyEvent::KnowledgeGap { sector, density, suggested_depth_range }) => {
                    gaps.push((sector, density, suggested_depth_range));
                }
                Ok(_) => continue, // skip non-gap events
                Err(tokio::sync::broadcast::error::TryRecvError::Empty) => break,
                Err(tokio::sync::broadcast::error::TryRecvError::Lagged(_)) => continue,
                Err(tokio::sync::broadcast::error::TryRecvError::Closed) => break,
            }
        }
        gaps
    }

    /// Generate TriggerDream intents for high-priority desires.
    ///
    /// For each desire above the threshold, find the nearest node to the
    /// gap sector and create a dream intent from that seed.
    fn generate_dream_intents(
        &self,
        desires: &[DesireSignal],
        storage: &GraphStorage,
    ) -> Vec<AgencyIntent> {
        let threshold = self.config.desire_dream_threshold;
        let depth = self.config.desire_dream_depth;

        // Only process top desire to avoid intent storm
        let top_desire = desires.iter().find(|d| d.priority >= threshold);

        let Some(desire) = top_desire else {
            return Vec::new();
        };

        // Find a seed node near the gap sector
        match find_seed_near_sector(storage, &desire.sector, &desire.depth_range) {
            Some(seed_id) => {
                tracing::info!(
                    desire_id  = %desire.id,
                    seed_node  = %seed_id,
                    priority   = desire.priority,
                    "desire→dream: triggering dream from desire"
                );
                vec![AgencyIntent::TriggerDream {
                    seed_node_id: seed_id,
                    depth,
                    reason: format!(
                        "desire priority={:.2}, sector=({},{}), query={}",
                        desire.priority,
                        desire.sector.depth_bin,
                        desire.sector.angular_bin,
                        desire.suggested_query,
                    ),
                }]
            }
            None => Vec::new(),
        }
    }

    /// Access the event bus for external subscribers.
    pub fn event_bus(&self) -> &AgencyEventBus {
        &self.bus
    }

    /// Ensure the Observer Identity meta-node exists in the graph.
    /// Call this once during initialization.
    /// Get a shared reference to the DirtySet for external mutation tracking.
    ///
    /// The server should call `dirty_set.mark(id)` after executing intents
    /// that modify node energy/metadata (HebbianLTP, HeatFlow, GravityPull, etc.).
    pub fn dirty_set(&self) -> std::sync::Arc<DirtySet> {
        std::sync::Arc::clone(&self.dirty_set)
    }

    pub fn ensure_observer_identity(
        &self,
        storage: &GraphStorage,
    ) -> Result<uuid::Uuid, AgencyError> {
        ObserverIdentity::ensure_exists(storage)
    }
}

/// Find a node near a given gap sector to use as a dream seed.
///
/// Scans NodeMeta (lightweight, no embeddings) and picks the highest-energy
/// node in or adjacent to the target sector. Uses UUID hash for angular bin
/// (same algorithm as the daemons).
fn find_seed_near_sector(
    storage: &GraphStorage,
    sector: &SectorId,
    depth_range: &(f32, f32),
) -> Option<uuid::Uuid> {
    let mut best: Option<(uuid::Uuid, f32)> = None;

    for result in storage.iter_nodes_meta() {
        let meta = match result {
            Ok(m) => m,
            Err(_) => continue,
        };

        // Compute angular bin from UUID hash (same as daemons)
        let mut hasher = DefaultHasher::new();
        meta.id.hash(&mut hasher);
        let hash = hasher.finish();
        let angular_bin = (hash % 16) as usize; // 16 sectors

        // Compute depth bin (5 bins in [0, 1])
        let depth_bin = (meta.depth.clamp(0.0, 0.999) * 5.0) as usize;

        // Check proximity: same or adjacent sector
        let angular_close = angular_bin == sector.angular_bin
            || angular_bin == (sector.angular_bin + 1) % 16
            || angular_bin == (sector.angular_bin + 15) % 16;
        let depth_close = depth_bin == sector.depth_bin
            || (depth_bin > 0 && depth_bin - 1 == sector.depth_bin)
            || depth_bin + 1 == sector.depth_bin;
        // Also accept if depth is in the requested range
        let in_range = meta.depth >= depth_range.0 && meta.depth <= depth_range.1;

        if (angular_close && depth_close) || in_range {
            let is_better = match best {
                None => true,
                Some((_, best_energy)) => meta.energy > best_energy,
            };
            if is_better {
                best = Some((meta.id, meta.energy));
            }
        }
    }

    best.map(|(id, _)| id)
}

/// Build a HebbianConfig from AgencyConfig fields.
fn build_hebbian_config(cfg: &AgencyConfig) -> HebbianConfig {
    HebbianConfig {
        ltp_rate: cfg.hebbian_ltp_rate,
        trace_decay: cfg.hebbian_trace_decay,
        trace_threshold: 0.1,
        max_weight: cfg.hebbian_max_weight,
        max_total_weight: 50.0,
        enabled: cfg.hebbian_enabled,
    }
}

/// Build a ThermodynamicsConfig from AgencyConfig fields.
fn build_thermo_config(cfg: &AgencyConfig) -> ThermodynamicsConfig {
    ThermodynamicsConfig {
        t_cold: cfg.thermo_t_cold,
        t_hot: cfg.thermo_t_hot,
        thermal_conductivity: cfg.thermo_conductivity,
        max_heat_flow: cfg.thermo_max_heat_flow,
        max_scan: cfg.ecan_max_scan.max(5_000),
        interval: cfg.thermo_interval,
        enable_heat_flow: cfg.thermo_enable_heat_flow,
    }
}

/// Build a GravityConfig from AgencyConfig fields.
fn build_gravity_config(cfg: &AgencyConfig) -> GravityConfig {
    GravityConfig {
        g_constant: cfg.gravity_g_constant,
        well_mass_threshold: cfg.gravity_well_threshold,
        max_pairs: cfg.gravity_max_pairs,
        top_k: 20,
        interval: cfg.gravity_interval,
        apply_pulls: cfg.gravity_apply_pulls,
        max_pull: 0.005,
        min_distance: 0.01,
        enabled: cfg.gravity_enabled,
    }
}

/// Build an EcanConfig from AgencyConfig fields.
fn build_ecan_config(cfg: &AgencyConfig) -> EcanConfig {
    EcanConfig {
        attention: AttentionConfig {
            max_scan: cfg.ecan_max_scan,
            budget_scale: cfg.ecan_budget_scale,
            demand_fraction: cfg.ecan_demand_fraction,
            energy_floor: cfg.ecan_energy_floor,
            max_bids_per_source: cfg.ecan_max_bids,
            attention_energy_gain: cfg.ecan_energy_gain,
            energy_decay: 0.97,
            emit_intents: true,
        },
        curiosity: CuriosityConfig {
            density_bins: 32,
            curiosity_budget_weight: 0.5,
            novelty_bid_weight: 1.0,
            curiosity_threshold: cfg.ecan_curiosity_threshold,
            max_exploration_ratio: cfg.ecan_max_explore_ratio,
        },
        interval: cfg.ecan_interval,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use nietzsche_graph::{Edge, EdgeType, GraphStorage, Node, PoincareVector, AdjacencyIndex};
    use tempfile::TempDir;
    use uuid::Uuid;

    fn open_storage(dir: &TempDir) -> GraphStorage {
        GraphStorage::open(dir.path().to_str().unwrap()).unwrap()
    }

    fn make_node(x: f32, y: f32, energy: f32) -> Node {
        let mut node = Node::new(
            Uuid::new_v4(),
            PoincareVector::new(vec![x, y]),
            serde_json::json!({}),
        );
        node.meta.energy = energy;
        node
    }

    #[test]
    fn full_tick_on_star_graph() {
        let dir = TempDir::new().unwrap();
        let storage = open_storage(&dir);
        let adjacency = AdjacencyIndex::new();

        // Star: center -> 10 leaves
        let center = make_node(0.05, 0.0, 0.9);
        let cid = center.id;
        storage.put_node(&center).unwrap();

        for i in 0..10 {
            let angle = i as f32 * std::f32::consts::TAU / 10.0;
            let leaf = make_node(0.4 * angle.cos(), 0.4 * angle.sin(), 0.6);
            let lid = leaf.id;
            storage.put_node(&leaf).unwrap();
            let edge = Edge::new(cid, lid, EdgeType::Association, 0.8);
            storage.put_edge(&edge).unwrap();
            adjacency.add_edge(&edge);
        }

        let config = AgencyConfig {
            observer_report_interval: 1, // report on first tick
            ..AgencyConfig::default()
        };
        let mut engine = AgencyEngine::new(config);
        let report = engine.tick(&storage, &adjacency).unwrap();

        // All daemons should have run
        assert_eq!(report.daemon_reports.len(), 8);
        for dr in &report.daemon_reports {
            assert!(dr.nodes_scanned > 0);
        }

        // Health report should be present (interval=1)
        assert!(report.health_report.is_some());
        let health = report.health_report.as_ref().unwrap();
        assert_eq!(health.total_nodes, 11);
        assert!(health.mean_energy > 0.0);

        // Health report should generate a PersistHealthReport intent
        assert!(report.intents.iter().any(|i| matches!(i, AgencyIntent::PersistHealthReport { .. })));
    }

    #[test]
    fn health_report_at_correct_interval() {
        let dir = TempDir::new().unwrap();
        let storage = open_storage(&dir);
        let adjacency = AdjacencyIndex::new();

        for i in 0..5 {
            let node = make_node(0.01 * (i + 1) as f32, 0.01, 0.5);
            storage.put_node(&node).unwrap();
        }

        let config = AgencyConfig {
            observer_report_interval: 3,
            ..AgencyConfig::default()
        };
        let mut engine = AgencyEngine::new(config);

        // Ticks 1, 2: no health report
        assert!(engine.tick(&storage, &adjacency).unwrap().health_report.is_none());
        assert!(engine.tick(&storage, &adjacency).unwrap().health_report.is_none());

        // Tick 3: health report
        assert!(engine.tick(&storage, &adjacency).unwrap().health_report.is_some());
    }

    #[test]
    fn from_env_creates_engine() {
        let engine = AgencyEngine::from_env();
        assert!(engine.config.tick_secs > 0);
    }

    #[test]
    fn empty_graph_no_panic() {
        let dir = TempDir::new().unwrap();
        let storage = open_storage(&dir);
        let adjacency = AdjacencyIndex::new();

        let config = AgencyConfig {
            observer_report_interval: 1,
            ..AgencyConfig::default()
        };
        let mut engine = AgencyEngine::new(config);
        let report = engine.tick(&storage, &adjacency).unwrap();

        assert_eq!(report.daemon_reports.len(), 8);
        for dr in &report.daemon_reports {
            assert_eq!(dr.nodes_scanned, 0);
        }
    }

    #[test]
    fn low_energy_triggers_sleep_intent() {
        let dir = TempDir::new().unwrap();
        let storage = open_storage(&dir);
        let adjacency = AdjacencyIndex::new();

        // Very low energy nodes
        for i in 0..10 {
            let node = make_node(0.01 * (i + 1) as f32, 0.01, 0.05);
            storage.put_node(&node).unwrap();
        }

        let config = AgencyConfig {
            observer_report_interval: 1,
            observer_wake_energy_threshold: 0.3,
            reactor_cooldown_ticks: 0,
            ..AgencyConfig::default()
        };
        let mut engine = AgencyEngine::new(config);
        let report = engine.tick(&storage, &adjacency).unwrap();

        // Should have a sleep intent from low energy wake-up
        assert!(
            report.intents.iter().any(|i| matches!(i, AgencyIntent::TriggerSleepCycle { .. })),
            "expected TriggerSleepCycle intent for low-energy graph, got: {:?}",
            report.intents
        );
    }

    #[test]
    fn observer_identity_created_on_tick() {
        let dir = TempDir::new().unwrap();
        let storage = open_storage(&dir);
        let adjacency = AdjacencyIndex::new();

        for i in 0..5 {
            let node = make_node(0.01 * (i + 1) as f32, 0.01, 0.6);
            storage.put_node(&node).unwrap();
        }

        let config = AgencyConfig {
            observer_report_interval: 1,
            ..AgencyConfig::default()
        };
        let mut engine = AgencyEngine::new(config);

        // Ensure observer identity is created
        let observer_id = engine.ensure_observer_identity(&storage).unwrap();
        let meta = storage.get_node_meta(&observer_id).unwrap().unwrap();
        assert!(ObserverIdentity::is_observer(&meta));

        // After a tick with health report, observer energy should be updated
        let _report = engine.tick(&storage, &adjacency).unwrap();
        let updated_meta = storage.get_node_meta(&observer_id).unwrap().unwrap();
        assert!(updated_meta.energy > 0.0);
    }
}
